In [1]:
import os, sys
import pandas as pd

In [2]:
sys.path.append('..')

In [43]:
missing_values = ["?"]

In [44]:
data_file = "sales_train.csv"
df = pd.read_csv("../data/"+data_file, na_values = missing_values)
df.head()

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
0,9160056,440000.0,16/04/2013,16/04/2013,1045.0,NaN,NaN,3.0,2.0,NaN,...,NaN,10,NaN,Marian,Street,NaN,Aireys Inlet,3231,VIC,930.0
1,17246721,355250.0,16/12/2014,16/12/2014,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11,NaN,Bowral,Grove,NaN,Jordan Springs,2747,NSW,425.0
2,12087127,285000.0,25/09/2011,26/05/2011,550.0,NaN,85.0,3.0,1.0,1.0,...,NaN,3B,NaN,Beckford,Close,NaN,East Cannington,6107,WA,550.0
3,5803664,687000.0,6/09/2013,29/08/2013,3051.0,NaN,82.0,2.0,1.0,1.0,...,NaN,41,NaN,Pitt,Street,NaN,Redfern,2016,NSW,3050.0
4,6828541,280000.0,15/10/2011,7/09/2011,645.0,NaN,NaN,3.0,1.0,2.0,...,NaN,58,NaN,Beeville,Road,NaN,Petrie,4502,QLD,645.0

In [45]:
import explore as ex
ex.get_type_dict(df)

{'object': ['CL_Transfer_Date',
  'Cl_History_From',
  'Cl_Materials_In_Roof',
  'Cl_Materials_In_External_Walls',
  'Cl_Materials_In_Floor',
  'Cl_Access_Security_Installed',
  'Cl_Air_Conditioned',
  'Cl_Architectural_Style',
  'Cl_Close_To_Public_Transport',
  'Cl_Condition',
  'Cl_Fireplace',
  'Cl_On_Main_Road',
  'Cl_Renovated',
  'Cl_Scenic_View',
  'Cl_Swimming_Pool',
  'Cl_Heritage_Flag',
  'CL_Property_Type',
  'CL_Unit_No',
  'CL_Unit_No_Derived',
  'CL_Street_No_Start',
  'CL_Street_Name',
  'CL_Street_Type',
  'CL_Street_Direction',
  'CL_Suburb',
  'CL_State'],
 'float64': ['CL_Contract_Price',
  'Cl_Est_Land_Area',
  'Cl_Equiv_Building_Area',
  'Cl_Floor_Area',
  'Cl_Bedrooms',
  'Cl_Bathrooms',
  'Cl_Car_Spaces',
  'Cl_Garages',
  'Cl_Year_Built',
  'Cl_Bond_Amount',
  'Cl_Construction_Type',
  'Cl_Dining_Rooms',
  'Cl_Ensuites',
  'Cl_Family_Rooms',
  'Cl_Floor_Level_Of_Unit',
  'Cl_Frontage',
  'Cl_Lounge_Rooms',
  'Cl_Street_Frontage_Size',
  'Cl_Games_Rooms',
  'Cl_Kitchens',
  'Cl_Meal_Rooms',
  'Cl_Study_Rooms',
  'Cl_Floor_Levels_Inside_Unit',
  'Cl_Toilets',
  'CL_Street_No_End',
  'CL_Land_Area'],
 'int64': ['Cl_Property_ID', 'CL_Postcode']}

In [4]:
import transform as tr
import utility as ut

In [6]:
(x, y, features) = ut.extract_feature_target(df, 'CL_Street_Type', todf=False)

In [7]:
x

array([['?', '?', '16/04/2013', ..., '?', '?', '?'],
       ['?', '?', '16/12/2014', ..., '?', '?', '?'],
       ['?', '?', '25/09/2011', ..., '?', '?', '1'],
       ...,
       ['3', '?', '21/11/2011', ..., '?', '1', '1'],
       ['?', '?', '8/07/2016', ..., '?', '?', '?'],
       ['?', '?', '15/03/2012', ..., '?', '?', '?']], dtype=object)

In [9]:
y[:5]

array(['Street', 'Grove', 'Close', 'Street', 'Road'], dtype=object)

### Value Remover

In [10]:
vr = tr.ValueRemover(['CL_State'], ['VIC'])

In [12]:
sdf = vr.fit_transform(df)
sdf.head()

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
1,17246721,355250,16/12/2014,16/12/2014,?,?,?,?,?,?,...,?,11,?,Bowral,Grove,?,Jordan Springs,2747,NSW,425
2,12087127,285000,25/09/2011,26/05/2011,550,?,85,3,1,1,...,?,3B,?,Beckford,Close,?,East Cannington,6107,WA,550
3,5803664,687000,6/09/2013,29/08/2013,3051,?,82,2,1,1,...,?,41,?,Pitt,Street,?,Redfern,2016,NSW,3050
4,6828541,280000,15/10/2011,7/09/2011,645,?,?,3,1,2,...,?,58,?,Beeville,Road,?,Petrie,4502,QLD,645
5,5148187,2100000,13/02/2013,13/02/2013,714,?,277,4,3,2,...,?,30A,?,Annette,Street,?,Oatley,2223,NSW,715

In [13]:
ex.count_levels(sdf, 'CL_State')

{'CL_State': [('ACT', 16),
  ('NSW', 321),
  ('NT', 3),
  ('QLD', 210),
  ('SA', 67),
  ('TAS', 23),
  ('WA', 90)]}

### Date Extractor

In [24]:
from imp import reload
reload(tr)

In [25]:
dx = tr.DateExtractor(['CL_Transfer_Date'], "%d/%m/%Y")

In [26]:
sdf = dx.fit_transform(df)
sdf.head()

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area,CL_Transfer_Date_Day,CL_Transfer_Date_Month,CL_Transfer_Date_Year,CL_Transfer_Date_Weekday
0,9160056,440000,16/04/2013,16/04/2013,1045,?,?,3,2,?,...,Street,?,Aireys Inlet,3231,VIC,930,16,4,2013,2
1,17246721,355250,16/12/2014,16/12/2014,?,?,?,?,?,?,...,Grove,?,Jordan Springs,2747,NSW,425,16,12,2014,2
2,12087127,285000,25/09/2011,26/05/2011,550,?,85,3,1,1,...,Close,?,East Cannington,6107,WA,550,25,9,2011,7
3,5803664,687000,6/09/2013,29/08/2013,3051,?,82,2,1,1,...,Street,?,Redfern,2016,NSW,3050,6,9,2013,5
4,6828541,280000,15/10/2011,7/09/2011,645,?,?,3,1,2,...,Road,?,Petrie,4502,QLD,645,15,10,2011,6

### Imputer

In [48]:
ex.count_missing(df)

{'Cl_Property_ID': 0,
 'CL_Contract_Price': 1,
 'CL_Transfer_Date': 0,
 'Cl_History_From': 0,
 'Cl_Est_Land_Area': 228,
 'Cl_Equiv_Building_Area': 965,
 'Cl_Floor_Area': 593,
 'Cl_Bedrooms': 155,
 'Cl_Bathrooms': 152,
 'Cl_Car_Spaces': 312,
 'Cl_Garages': 443,
 'Cl_Year_Built': 581,
 'Cl_Materials_In_Roof': 598,
 'Cl_Materials_In_External_Walls': 598,
 'Cl_Materials_In_Floor': 772,
 'Cl_Bond_Amount': 798,
 'Cl_Access_Security_Installed': 920,
 'Cl_Air_Conditioned': 592,
 'Cl_Architectural_Style': 958,
 'Cl_Close_To_Public_Transport': 927,
 'Cl_Condition': 964,
 'Cl_Construction_Type': 1000,
 'Cl_Dining_Rooms': 834,
 'Cl_Ensuites': 719,
 'Cl_Family_Rooms': 901,
 'Cl_Fireplace': 933,
 'Cl_Floor_Level_Of_Unit': 977,
 'Cl_Frontage': 971,
 'Cl_Lounge_Rooms': 822,
 'Cl_Street_Frontage_Size': 970,
 'Cl_Games_Rooms': 985,
 'Cl_Kitchens': 929,
 'Cl_Meal_Rooms': 984,
 'Cl_Study_Rooms': 942,
 'Cl_Floor_Levels_Inside_Unit': 963,
 'Cl_On_Main_Road': 934,
 'Cl_Renovated': 972,
 'Cl_Scenic_View': 921,
 'Cl_Swimming_Pool': 861,
 'Cl_Toilets': 801,
 'Cl_Heritage_Flag': 999,
 'CL_Property_Type': 0,
 'CL_Unit_No': 704,
 'CL_Unit_No_Derived': 998,
 'CL_Street_No_Start': 7,
 'CL_Street_No_End': 931,
 'CL_Street_Name': 0,
 'CL_Street_Type': 8,
 'CL_Street_Direction': 993,
 'CL_Suburb': 0,
 'CL_Postcode': 0,
 'CL_State': 0,
 'CL_Land_Area': 174}

In [46]:
t = tr.ConstantImputer(numerical_columns=['Cl_Est_Land_Area'])

In [47]:
sdf = t.fit_transform(df)
sdf.head()

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
0,9160056,440000.0,16/04/2013,16/04/2013,1045.0,NaN,NaN,3.0,2.0,NaN,...,missing_value,10,NaN,Marian,Street,missing_value,Aireys Inlet,3231,VIC,930.0
1,17246721,355250.0,16/12/2014,16/12/2014,0.0,NaN,NaN,NaN,NaN,NaN,...,missing_value,11,NaN,Bowral,Grove,missing_value,Jordan Springs,2747,NSW,425.0
2,12087127,285000.0,25/09/2011,26/05/2011,550.0,NaN,85.0,3.0,1.0,1.0,...,missing_value,3B,NaN,Beckford,Close,missing_value,East Cannington,6107,WA,550.0
3,5803664,687000.0,6/09/2013,29/08/2013,3051.0,NaN,82.0,2.0,1.0,1.0,...,missing_value,41,NaN,Pitt,Street,missing_value,Redfern,2016,NSW,3050.0
4,6828541,280000.0,15/10/2011,7/09/2011,645.0,NaN,NaN,3.0,1.0,2.0,...,missing_value,58,NaN,Beeville,Road,missing_value,Petrie,4502,QLD,645.0

In [51]:
ex.count_missing(df)['Cl_Materials_In_Roof']

598

In [53]:
df['Cl_Materials_In_Roof']

0                                NaN
1                                NaN
2                               Tile
3                              Other
4                                NaN
                   ...
995                              NaN
996                           D/Tile
997    Suspended Reinforced Concrete
998                    Concrete Tile
999                             Tile
Name: Cl_Materials_In_Roof, Length: 1000, dtype: object

In [49]:
t = tr.ConstantImputer(categorical_columns=['Cl_Materials_In_Roof'])

In [50]:
sdf = t.fit_transform(df)
sdf['Cl_Materials_In_Roof']

0                      missing_value
1                      missing_value
2                               Tile
3                              Other
4                      missing_value
                   ...
995                    missing_value
996                           D/Tile
997    Suspended Reinforced Concrete
998                    Concrete Tile
999                             Tile
Name: Cl_Materials_In_Roof, Length: 1000, dtype: object

In [52]:
ex.count_missing(sdf)['Cl_Materials_In_Roof']

0

In [54]:
ex.get_column_type(df)

{'binary': ['Cl_Air_Conditioned',
  'Cl_Fireplace',
  'Cl_Study_Rooms',
  'Cl_Family_Rooms',
  'Cl_Kitchens',
  'Cl_Access_Security_Installed',
  'Cl_Floor_Levels_Inside_Unit'],
 'categorical': ['CL_Street_Direction',
  'Cl_Floor_Level_Of_Unit',
  'CL_Transfer_Date',
  'Cl_Dining_Rooms',
  'Cl_History_From',
  'Cl_On_Main_Road',
  'Cl_Condition',
  'CL_State',
  'CL_Property_Type',
  'Cl_Materials_In_Roof',
  'Cl_Heritage_Flag',
  'CL_Suburb',
  'Cl_Close_To_Public_Transport',
  'Cl_Construction_Type',
  'Cl_Meal_Rooms',
  'Cl_Scenic_View',
  'CL_Street_No_Start',
  'CL_Unit_No_Derived',
  'Cl_Ensuites',
  'CL_Street_Type',
  'Cl_Materials_In_External_Walls',
  'Cl_Bedrooms',
  'Cl_Swimming_Pool',
  'Cl_Games_Rooms',
  'Cl_Bathrooms',
  'Cl_Materials_In_Floor',
  'Cl_Lounge_Rooms',
  'CL_Street_Name',
  'Cl_Renovated',
  'Cl_Toilets',
  'CL_Unit_No',
  'Cl_Architectural_Style',
  'Cl_Garages'],
 'numerical': ['CL_Street_No_End',
  'Cl_Equiv_Building_Area',
  'Cl_Est_Land_Area',
  'CL_Land_Area',
  'CL_Contract_Price',
  'Cl_Car_Spaces',
  'Cl_Property_ID',
  'Cl_Bond_Amount',
  'Cl_Frontage',
  'Cl_Floor_Area',
  'Cl_Year_Built',
  'Cl_Street_Frontage_Size',
  'CL_Postcode']}

In [58]:
reload(tr)

In [59]:
t = tr.ConstantImputer()
sdf = t.fit_transform(df)

In [60]:
ex.count_missing(sdf)

{'Cl_Property_ID': 0,
 'CL_Contract_Price': 0,
 'CL_Transfer_Date': 0,
 'Cl_History_From': 0,
 'Cl_Est_Land_Area': 0,
 'Cl_Equiv_Building_Area': 0,
 'Cl_Floor_Area': 0,
 'Cl_Bedrooms': 0,
 'Cl_Bathrooms': 0,
 'Cl_Car_Spaces': 0,
 'Cl_Garages': 0,
 'Cl_Year_Built': 0,
 'Cl_Materials_In_Roof': 0,
 'Cl_Materials_In_External_Walls': 0,
 'Cl_Materials_In_Floor': 0,
 'Cl_Bond_Amount': 0,
 'Cl_Access_Security_Installed': 0,
 'Cl_Air_Conditioned': 0,
 'Cl_Architectural_Style': 0,
 'Cl_Close_To_Public_Transport': 0,
 'Cl_Condition': 0,
 'Cl_Construction_Type': 0,
 'Cl_Dining_Rooms': 0,
 'Cl_Ensuites': 0,
 'Cl_Family_Rooms': 0,
 'Cl_Fireplace': 0,
 'Cl_Floor_Level_Of_Unit': 0,
 'Cl_Frontage': 0,
 'Cl_Lounge_Rooms': 0,
 'Cl_Street_Frontage_Size': 0,
 'Cl_Games_Rooms': 0,
 'Cl_Kitchens': 0,
 'Cl_Meal_Rooms': 0,
 'Cl_Study_Rooms': 0,
 'Cl_Floor_Levels_Inside_Unit': 0,
 'Cl_On_Main_Road': 0,
 'Cl_Renovated': 0,
 'Cl_Scenic_View': 0,
 'Cl_Swimming_Pool': 0,
 'Cl_Toilets': 0,
 'Cl_Heritage_Flag': 0,
 'CL_Property_Type': 0,
 'CL_Unit_No': 0,
 'CL_Unit_No_Derived': 0,
 'CL_Street_No_Start': 0,
 'CL_Street_No_End': 0,
 'CL_Street_Name': 0,
 'CL_Street_Type': 0,
 'CL_Street_Direction': 0,
 'CL_Suburb': 0,
 'CL_Postcode': 0,
 'CL_State': 0,
 'CL_Land_Area': 0}

### DataFrame Imputer

In [84]:
reload(tr)

In [85]:
t = tr.DataFrameImputer()
sdf = t.fit_transform(df)

In [86]:
sdf.head()

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
0,9160056,440000.0,16/04/2013,16/04/2013,1045.000000,125.0,153.226044,3.0,2.0,1.863372,...,N,10,127.014493,Marian,Street,West,Aireys Inlet,3231,VIC,930.0
1,17246721,355250.0,16/12/2014,16/12/2014,11589.967617,125.0,153.226044,3.0,2.0,1.863372,...,N,11,127.014493,Bowral,Grove,West,Jordan Springs,2747,NSW,425.0
2,12087127,285000.0,25/09/2011,26/05/2011,550.000000,125.0,85.000000,3.0,1.0,1.000000,...,N,3B,127.014493,Beckford,Close,West,East Cannington,6107,WA,550.0
3,5803664,687000.0,6/09/2013,29/08/2013,3051.000000,125.0,82.000000,2.0,1.0,1.000000,...,N,41,127.014493,Pitt,Street,West,Redfern,2016,NSW,3050.0
4,6828541,280000.0,15/10/2011,7/09/2011,645.000000,125.0,153.226044,3.0,1.0,2.000000,...,N,58,127.014493,Beeville,Road,West,Petrie,4502,QLD,645.0

In [100]:
reload(ex)

In [101]:
ex.any_missing(df)

True

In [104]:
ex.any_missing(sdf)

False

In [102]:
ex.get_missing_columns(df)

['CL_Contract_Price',
 'Cl_Est_Land_Area',
 'Cl_Equiv_Building_Area',
 'Cl_Floor_Area',
 'Cl_Bedrooms',
 'Cl_Bathrooms',
 'Cl_Car_Spaces',
 'Cl_Garages',
 'Cl_Year_Built',
 'Cl_Materials_In_Roof',
 'Cl_Materials_In_External_Walls',
 'Cl_Materials_In_Floor',
 'Cl_Bond_Amount',
 'Cl_Access_Security_Installed',
 'Cl_Air_Conditioned',
 'Cl_Architectural_Style',
 'Cl_Close_To_Public_Transport',
 'Cl_Condition',
 'Cl_Construction_Type',
 'Cl_Dining_Rooms',
 'Cl_Ensuites',
 'Cl_Family_Rooms',
 'Cl_Fireplace',
 'Cl_Floor_Level_Of_Unit',
 'Cl_Frontage',
 'Cl_Lounge_Rooms',
 'Cl_Street_Frontage_Size',
 'Cl_Games_Rooms',
 'Cl_Kitchens',
 'Cl_Meal_Rooms',
 'Cl_Study_Rooms',
 'Cl_Floor_Levels_Inside_Unit',
 'Cl_On_Main_Road',
 'Cl_Renovated',
 'Cl_Scenic_View',
 'Cl_Swimming_Pool',
 'Cl_Toilets',
 'Cl_Heritage_Flag',
 'CL_Unit_No',
 'CL_Unit_No_Derived',
 'CL_Street_No_Start',
 'CL_Street_No_End',
 'CL_Street_Type',
 'CL_Street_Direction',
 'CL_Land_Area']

In [103]:
ex.get_missing_columns(sdf)

[]

### Column Remover

In [106]:
t = tr.ColumnRemover( ['CL_Street_Direction'])
sdf = t.fit_transform(df)

In [111]:
sdf.shape

(1000, 52)

In [112]:
df.shape

(1000, 53)

### Create data frame

In [116]:
t =tr.CreateDataFrame(['a', 'b'])

In [117]:
t.fit_transform([[1,2]])

   a  b
0  1  2

### Encoder

In [205]:
reload(tr)

In [206]:
t = tr.Encoder(todf=False)
t.fit_transform(df[['CL_Suburb']])

array([[  2],
       [361],
       [241],
       [598],
       [570],
       [539],
       [504],
       [ 80],
       [677],
       [393],
       [691],
       [110],
       [798],
       [281],
       [662],
       [257],
       [131],
       [157],
       [309],
       [466],
       [702],
       [ 55],
       [ 30],
       [384],
       [509],
       [256],
       [364],
       [264],
       [385],
       [144],
       [ 39],
       [263],
       [ 75],
       [681],
       [170],
       [787],
       [673],
       [174],
       [634],
       [484],
       [232],
       [700],
       [500],
       [ 34],
       [221],
       [412],
       [ 99],
       [540],
       [275],
       [743],
       [334],
       [186],
       [496],
       [ 24],
       [550],
       [377],
       [710],
       [139],
       [552],
       [773],
       [197],
       [495],
       [667],
       [368],
       [396],
       [556],
       [ 13],
       [588],
       [454],
       [ 71],
       [380],
       [181],
       [308],
       [244],
       [574],
       [104],
       [267],
       [788],
       [254],
       [761],
       [601],
       [594],
       [132],
       [535],
       [274],
       [380],
       [693],
       [654],
       [245],
       [305],
       [515],
       [189],
       [ 11],
       [256],
       [155],
       [473],
       [122],
       [501],
       [370],
       [ 48],
       [146],
       [600],
       [ 51],
       [599],
       [501],
       [ 10],
       [ 47],
       [320],
       [ 78],
       [483],
       [119],
       [242],
       [ 70],
       [684],
       [212],
       [605],
       [532],
       [658],
       [282],
       [624],
       [277],
       [350],
       [224],
       [429],
       [379],
       [554],
       [ 61],
       [211],
       [ 15],
       [203],
       [174],
       [106],
       [ 29],
       [124],
       [407],
       [ 77],
       [732],
       [528],
       [184],
       [418],
       [618],
       [ 67],
       [421],
       [167],
       [208],
       [516],
       [502],
       [665],
       [218],
       [511],
       [130],
       [719],
       [426],
       [752],
       [631],
       [632],
       [ 93],
       [686],
       [ 80],
       [162],
       [638],
       [720],
       [771],
       [437],
       [142],
       [ 17],
       [ 39],
       [153],
       [576],
       [199],
       [537],
       [507],
       [758],
       [180],
       [397],
       [481],
       [618],
       [226],
       [731],
       [134],
       [ 36],
       [692],
       [516],
       [386],
       [373],
       [354],
       [417],
       [558],
       [166],
       [312],
       [485],
       [457],
       [434],
       [742],
       [552],
       [295],
       [111],
       [594],
       [171],
       [659],
       [365],
       [704],
       [164],
       [440],
       [182],
       [486],
       [ 49],
       [326],
       [121],
       [620],
       [544],
       [169],
       [546],
       [444],
       [246],
       [428],
       [543],
       [303],
       [100],
       [418],
       [179],
       [433],
       [113],
       [533],
       [ 46],
       [619],
       [149],
       [646],
       [123],
       [503],
       [744],
       [703],
       [778],
       [523],
       [256],
       [630],
       [  8],
       [548],
       [755],
       [310],
       [301],
       [614],
       [133],
       [403],
       [214],
       [714],
       [ 44],
       [344],
       [195],
       [628],
       [248],
       [229],
       [ 66],
       [109],
       [305],
       [493],
       [422],
       [ 87],
       [265],
       [501],
       [291],
       [447],
       [ 33],
       [676],
       [371],
       [286],
       [432],
       [200],
       [227],
       [190],
       [447],
       [473],
       [639],
       [384],
       [165],
       [260],
       [288],
       [506],
       [512],
       [662],
       [378],
       [772],
       [ 36],
       [151],
       [306],
       [165],
       [355],
       [ 36],
       [450],
       [483],
       [160],
       [236],
       [445],
       [229],
       [718],
       [800],
       [696],
       [279],
       [462],
       [299],
       [722],
       [402],
       [763],
       [110],
       [668],
       [669],
       [695],
       [353],
       [765],
       [358],
       [206],
       [706],
       [729],
       [ 57],
       [489],
       [246],
       [ 76],
       [603],
       [744],
       [357],
       [577],
       [193],
       [ 20],
       [141],
       [361],
       [376],
       [721],
       [252],
       [441],
       [505],
       [387],
       [673],
       [425],
       [405],
       [ 10],
       [276],
       [494],
       [ 56],
       [776],
       [464],
       [787],
       [215],
       [193],
       [636],
       [612],
       [418],
       [ 60],
       [147],
       [ 28],
       [163],
       [420],
       [ 98],
       [116],
       [ 74],
       [230],
       [478],
       [728],
       [672],
       [689],
       [525],
       [ 94],
       [105],
       [136],
       [331],
       [639],
       [769],
       [738],
       [235],
       [460],
       [640],
       [753],
       [307],
       [210],
       [ 21],
       [ 84],
       [411],
       [582],
       [615],
       [399],
       [751],
       [352],
       [731],
       [268],
       [787],
       [328],
       [406],
       [ 42],
       [104],
       [ 85],
       [656],
       [ 45],
       [337],
       [304],
       [332],
       [768],
       [110],
       [343],
       [754],
       [764],
       [796],
       [762],
       [708],
       [ 36],
       [557],
       [159],
       [208],
       [144],
       [ 25],
       [490],
       [597],
       [655],
       [513],
       [573],
       [617],
       [476],
       [ 12],
       [ 20],
       [348],
       [ 62],
       [477],
       [797],
       [793],
       [711],
       [508],
       [470],
       [748],
       [231],
       [269],
       [458],
       [340],
       [675],
       [783],
       [741],
       [ 72],
       [ 28],
       [499],
       [401],
       [520],
       [ 75],
       [510],
       [338],
       [ 89],
       [522],
       [730],
       [137],
       [296],
       [ 53],
       [670],
       [701],
       [ 22],
       [682],
       [687],
       [560],
       [427],
       [391],
       [129],
       [563],
       [188],
       [518],
       [460],
       [647],
       [ 24],
       [ 60],
       [666],
       [791],
       [472],
       [399],
       [602],
       [705],
       [278],
       [159],
       [767],
       [ 19],
       [315],
       [ 37],
       [781],
       [474],
       [345],
       [750],
       [283],
       [772],
       [394],
       [ 38],
       [497],
       [ 54],
       [140],
       [213],
       [595],
       [565],
       [553],
       [290],
       [718],
       [ 82],
       [226],
       [  4],
       [272],
       [216],
       [718],
       [220],
       [ 97],
       [740],
       [366],
       [578],
       [116],
       [121],
       [102],
       [583],
       [517],
       [270],
       [644],
       [547],
       [334],
       [623],
       [717],
       [159],
       [739],
       [297],
       [726],
       [458],
       [419],
       [601],
       [746],
       [566],
       [253],
       [ 51],
       [605],
       [178],
       [583],
       [498],
       [563],
       [204],
       [165],
       [660],
       [579],
       [209],
       [768],
       [ 33],
       [527],
       [ 92],
       [ 35],
       [452],
       [629],
       [404],
       [503],
       [112],
       [194],
       [673],
       [ 81],
       [505],
       [694],
       [698],
       [451],
       [569],
       [562],
       [258],
       [471],
       [174],
       [158],
       [727],
       [263],
       [540],
       [799],
       [266],
       [392],
       [514],
       [  0],
       [423],
       [661],
       [ 23],
       [621],
       [593],
       [526],
       [148],
       [ 28],
       [759],
       [789],
       [  6],
       [545],
       [452],
       [ 16],
       [443],
       [400],
       [539],
       [536],
       [125],
       [606],
       [484],
       [714],
       [674],
       [ 30],
       [547],
       [197],
       [463],
       [469],
       [571],
       [657],
       [ 73],
       [152],
       [487],
       [652],
       [205],
       [ 43],
       [779],
       [169],
       [247],
       [661],
       [568],
       [359],
       [689],
       [691],
       [135],
       [256],
       [766],
       [465],
       [ 89],
       [647],
       [649],
       [146],
       [449],
       [243],
       [524],
       [675],
       [356],
       [541],
       [306],
       [334],
       [187],
       [ 62],
       [713],
       [549],
       [712],
       [369],
       [327],
       [725],
       [424],
       [302],
       [240],
       [ 60],
       [791],
       [448],
       [436],
       [408],
       [ 38],
       [ 32],
       [322],
       [642],
       [191],
       [132],
       [280],
       [480],
       [176],
       [650],
       [330],
       [345],
       [611],
       [794],
       [664],
       [256],
       [589],
       [ 60],
       [383],
       [284],
       [587],
       [300],
       [680],
       [507],
       [538],
       [166],
       [461],
       [697],
       [ 41],
       [459],
       [511],
       [202],
       [685],
       [500],
       [444],
       [780],
       [492],
       [261],
       [757],
       [ 83],
       [ 73],
       [591],
       [690],
       [335],
       [ 80],
       [567],
       [791],
       [206],
       [149],
       [101],
       [357],
       [756],
       [724],
       [419],
       [361],
       [648],
       [  3],
       [255],
       [262],
       [724],
       [143],
       [786],
       [795],
       [ 90],
       [403],
       [517],
       [319],
       [314],
       [196],
       [298],
       [558],
       [336],
       [ 21],
       [756],
       [224],
       [580],
       [446],
       [435],
       [715],
       [241],
       [ 50],
       [456],
       [355],
       [453],
       [747],
       [597],
       [438],
       [238],
       [707],
       [782],
       [198],
       [777],
       [138],
       [586],
       [374],
       [ 73],
       [108],
       [170],
       [103],
       [660],
       [519],
       [649],
       [360],
       [479],
       [339],
       [589],
       [653],
       [207],
       [228],
       [738],
       [287],
       [790],
       [775],
       [633],
       [103],
       [430],
       [363],
       [228],
       [237],
       [114],
       [467],
       [795],
       [381],
       [678],
       [175],
       [580],
       [415],
       [219],
       [375],
       [616],
       [311],
       [126],
       [581],
       [172],
       [318],
       [273],
       [693],
       [635],
       [ 83],
       [747],
       [607],
       [271],
       [604],
       [349],
       [324],
       [785],
       [625],
       [760],
       [112],
       [177],
       [306],
       [ 63],
       [609],
       [ 51],
       [289],
       [610],
       [699],
       [ 68],
       [691],
       [588],
       [534],
       [ 18],
       [396],
       [294],
       [156],
       [629],
       [689],
       [409],
       [468],
       [551],
       [117],
       [553],
       [735],
       [ 33],
       [555],
       [666],
       [413],
       [347],
       [292],
       [688],
       [  5],
       [150],
       [329],
       [259],
       [128],
       [787],
       [316],
       [563],
       [521],
       [201],
       [622],
       [133],
       [ 96],
       [ 79],
       [322],
       [218],
       [709],
       [613],
       [ 86],
       [211],
       [626],
       [784],
       [637],
       [529],
       [683],
       [285],
       [763],
       [716],
       [ 23],
       [494],
       [150],
       [114],
       [239],
       [388],
       [120],
       [538],
       [564],
       [145],
       [112],
       [373],
       [ 33],
       [671],
       [ 27],
       [410],
       [218],
       [248],
       [166],
       [208],
       [563],
       [663],
       [723],
       [293],
       [ 64],
       [734],
       [118],
       [709],
       [249],
       [ 14],
       [372],
       [  1],
       [399],
       [351],
       [679],
       [442],
       [ 53],
       [ 40],
       [362],
       [  7],
       [225],
       [107],
       [578],
       [323],
       [ 60],
       [651],
       [ 70],
       [590],
       [737],
       [ 69],
       [106],
       [ 20],
       [341],
       [223],
       [584],
       [499],
       [455],
       [721],
       [745],
       [222],
       [ 88],
       [ 89],
       [342],
       [127],
       [689],
       [321],
       [226],
       [161],
       [689],
       [585],
       [185],
       [173],
       [766],
       [596],
       [192],
       [ 86],
       [346],
       [333],
       [645],
       [ 52],
       [659],
       [475],
       [473],
       [ 95],
       [183],
       [317],
       [115],
       [  9],
       [217],
       [149],
       [123],
       [467],
       [515],
       [389],
       [542],
       [154],
       [ 65],
       [774],
       [568],
       [733],
       [414],
       [398],
       [559],
       [553],
       [608],
       [ 31],
       [313],
       [382],
       [609],
       [416],
       [641],
       [290],
       [ 26],
       [792],
       [431],
       [754],
       [234],
       [770],
       [736],
       [561],
       [168],
       [488],
       [702],
       [152],
       [491],
       [395],
       [233],
       [627],
       [643],
       [458],
       [325],
       [439],
       [367],
       [502],
       [ 58],
       [250],
       [390],
       [572],
       [482],
       [749],
       [592],
       [ 59],
       [575],
       [251],
       [449],
       [660],
       [  4],
       [ 91],
       [530],
       [531]])

In [207]:
t = tr.Encoder(todf=True)
t.fit_transform(df[['CL_Suburb']])

     CL_Suburb
0            2
1          361
2          241
3          598
4          570
..         ...
995        660
996          4
997         91
998        530
999        531

[1000 rows x 1 columns]

In [144]:
df[['CL_Street_Type']]

    CL_Street_Type
0           Street
1            Grove
2            Close
3           Street
4             Road
..             ...
995         Street
996         Street
997         Avenue
998        Circuit
999         Street

[1000 rows x 1 columns]

In [166]:
t = tr.ConstantImputer(categorical_columns=['CL_Street_Type'])
sdf = t.fit_transform(df)

## FIXME:  mixed type

In [169]:
# mixed type...
ex.get_distinct_value(df, cols=['CL_Street_Type'])

{'CL_Street_Type': array(['Street', 'Grove', 'Close', 'Road', 'Place', 'Lane', 'Court',
        'Avenue', 'Way', 'Parade', 'Walk', 'Drive', 'Circuit', 'Link',
        'Highway', 'Crescent', 'Terrace', 'Boulevard', 'Mews', nan,
        'Circle', 'Loop', 'STREET', 'CIRCLE', 'Bend', 'Parkway', 'Quay',
        'ROAD', 'Gardens', 'Run', 'Green', 'DRIVE', 'PLACE', 'Chase',
        'WAY', 'Ramble', 'Corner', 'GROVE', 'Vista'], dtype=object)}

In [167]:
ex.get_distinct_value(sdf, cols=['CL_Street_Type'])

{'CL_Street_Type': array(['Street', 'Grove', 'Close', 'Road', 'Place', 'Lane', 'Court',
        'Avenue', 'Way', 'Parade', 'Walk', 'Drive', 'Circuit', 'Link',
        'Highway', 'Crescent', 'Terrace', 'Boulevard', 'Mews',
        'missing_value', 'Circle', 'Loop', 'STREET', 'CIRCLE', 'Bend',
        'Parkway', 'Quay', 'ROAD', 'Gardens', 'Run', 'Green', 'DRIVE',
        'PLACE', 'Chase', 'WAY', 'Ramble', 'Corner', 'GROVE', 'Vista'],
       dtype=object)}

In [168]:
t = tr.Encoder()
t.fit_transform(sdf[['CL_Street_Type']])

     CL_Street_Type
0                32
1                16
2                 7
3                32
4                29
..              ...
995              32
996              32
997               0
998               6
999              32

[1000 rows x 1 columns]

In [157]:
ex.get_distinct_value(df, cols=['CL_Street_Type', 'Cl_Toilets'])

{'CL_Street_Type': array(['Street', 'Grove', 'Close', 'Road', 'Place', 'Lane', 'Court',
        'Avenue', 'Way', 'Parade', 'Walk', 'Drive', 'Circuit', 'Link',
        'Highway', 'Crescent', 'Terrace', 'Boulevard', 'Mews', nan,
        'Circle', 'Loop', 'STREET', 'CIRCLE', 'Bend', 'Parkway', 'Quay',
        'ROAD', 'Gardens', 'Run', 'Green', 'DRIVE', 'PLACE', 'Chase',
        'WAY', 'Ramble', 'Corner', 'GROVE', 'Vista'], dtype=object),
 'Cl_Toilets': array([nan,  1.,  2.,  3.,  4.,  5.])}

In [153]:
ex.get_missing_columns(df)

['CL_Contract_Price',
 'Cl_Est_Land_Area',
 'Cl_Equiv_Building_Area',
 'Cl_Floor_Area',
 'Cl_Bedrooms',
 'Cl_Bathrooms',
 'Cl_Car_Spaces',
 'Cl_Garages',
 'Cl_Year_Built',
 'Cl_Materials_In_Roof',
 'Cl_Materials_In_External_Walls',
 'Cl_Materials_In_Floor',
 'Cl_Bond_Amount',
 'Cl_Access_Security_Installed',
 'Cl_Air_Conditioned',
 'Cl_Architectural_Style',
 'Cl_Close_To_Public_Transport',
 'Cl_Condition',
 'Cl_Construction_Type',
 'Cl_Dining_Rooms',
 'Cl_Ensuites',
 'Cl_Family_Rooms',
 'Cl_Fireplace',
 'Cl_Floor_Level_Of_Unit',
 'Cl_Frontage',
 'Cl_Lounge_Rooms',
 'Cl_Street_Frontage_Size',
 'Cl_Games_Rooms',
 'Cl_Kitchens',
 'Cl_Meal_Rooms',
 'Cl_Study_Rooms',
 'Cl_Floor_Levels_Inside_Unit',
 'Cl_On_Main_Road',
 'Cl_Renovated',
 'Cl_Scenic_View',
 'Cl_Swimming_Pool',
 'Cl_Toilets',
 'Cl_Heritage_Flag',
 'CL_Unit_No',
 'CL_Unit_No_Derived',
 'CL_Street_No_Start',
 'CL_Street_No_End',
 'CL_Street_Type',
 'CL_Street_Direction',
 'CL_Land_Area']

In [156]:
t.fit_transform(df[['Cl_Toilets']])

     Cl_Toilets
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
995         NaN
996         NaN
997         NaN
998         NaN
999         NaN

[1000 rows x 1 columns]

In [138]:
t.fit_transform(df[['CL_State', 'CL_Suburb']])

     CL_State  CL_Suburb
0           6          2
1           1        361
2           7        241
3           1        598
4           3        570
..        ...        ...
995         6        660
996         7          4
997         3         91
998         6        530
999         7        531

[1000 rows x 2 columns]

In [159]:
t.fit_dict

defaultdict(sklearn.preprocessing._label.LabelEncoder,
            {'CL_Street_Type': LabelEncoder()})

### TypeSelector

In [187]:
reload(tr)

In [188]:
t = tr.TypeSelector("categorical", todf=True)

In [189]:
sdf = t.fit_transform(df)

In [191]:
sdf.head()

,CL_Street_Direction,Cl_Floor_Level_Of_Unit,CL_Transfer_Date,Cl_Dining_Rooms,Cl_History_From,Cl_On_Main_Road,Cl_Condition,CL_State,CL_Property_Type,Cl_Materials_In_Roof,...,Cl_Games_Rooms,Cl_Bathrooms,Cl_Materials_In_Floor,Cl_Lounge_Rooms,CL_Street_Name,Cl_Renovated,Cl_Toilets,CL_Unit_No,Cl_Architectural_Style,Cl_Garages
0,NaN,NaN,16/04/2013,NaN,16/04/2013,NaN,NaN,VIC,House,NaN,...,NaN,2.0,NaN,NaN,Marian,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,16/12/2014,NaN,16/12/2014,NaN,NaN,NSW,House,NaN,...,NaN,NaN,NaN,NaN,Bowral,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,25/09/2011,1.0,26/05/2011,NaN,NaN,WA,Unit,Tile,...,NaN,1.0,NaN,1.0,Beckford,NaN,NaN,NaN,NaN,1.0
3,NaN,NaN,6/09/2013,NaN,29/08/2013,NaN,NaN,NSW,Unit,Other,...,NaN,1.0,Tiled Floor Timber Floor,NaN,Pitt,NaN,NaN,33,NaN,1.0
4,NaN,NaN,15/10/2011,NaN,7/09/2011,NaN,NaN,QLD,House,NaN,...,NaN,1.0,Timber Floor,NaN,Beeville,NaN,NaN,NaN,NaN,2.0

In [192]:
ex.get_column_type(sdf)

{'binary': [],
 'categorical': ['CL_Street_Direction',
  'Cl_Floor_Level_Of_Unit',
  'CL_Transfer_Date',
  'Cl_Dining_Rooms',
  'Cl_History_From',
  'Cl_On_Main_Road',
  'Cl_Condition',
  'CL_State',
  'CL_Property_Type',
  'Cl_Materials_In_Roof',
  'Cl_Heritage_Flag',
  'CL_Suburb',
  'Cl_Close_To_Public_Transport',
  'Cl_Construction_Type',
  'Cl_Meal_Rooms',
  'Cl_Scenic_View',
  'CL_Street_No_Start',
  'CL_Unit_No_Derived',
  'Cl_Ensuites',
  'CL_Street_Type',
  'Cl_Materials_In_External_Walls',
  'Cl_Bedrooms',
  'Cl_Swimming_Pool',
  'Cl_Games_Rooms',
  'Cl_Bathrooms',
  'Cl_Materials_In_Floor',
  'Cl_Lounge_Rooms',
  'Cl_Toilets',
  'CL_Street_Name',
  'Cl_Renovated',
  'CL_Unit_No',
  'Cl_Architectural_Style',
  'Cl_Garages'],
 'numerical': []}

### Function Transformer

In [212]:
reload(tr)

In [223]:
t = tr.FunctionTransformer(ex.get_distinct_value)

In [224]:
t.fit_transform(sdf)

{'CL_Street_Direction': array([nan, 'East', 'North', 'West'], dtype=object),
 'Cl_Floor_Level_Of_Unit': array([nan,  2.,  4.,  1., 48., 45.,  6.,  8.,  3.]),
 'CL_Transfer_Date': array(['16/04/2013', '16/12/2014', '25/09/2011', '6/09/2013',
        '15/10/2011', '13/02/2013', '7/12/2011', '9/10/2010', '14/02/2017',
        '21/11/2015', '22/10/2011', '31/05/2015', '23/12/2016',
        '8/03/2019', '28/02/2012', '3/02/2017', '28/03/2011', '4/05/2017',
        '8/08/2016', '26/03/2013', '11/06/2015', '22/10/2013',
        '10/06/2015', '28/09/2013', '4/01/2011', '6/03/2012', '16/10/2014',
        '23/04/2018', '10/06/2011', '21/06/2017', '16/06/2017',
        '23/11/2012', '27/09/2019', '21/04/2016', '10/08/2017',
        '12/10/2017', '6/02/2013', '30/05/2015', '6/04/2011', '25/01/2012',
        '24/09/2014', '6/06/2015', '5/04/2012', '19/08/2017', '14/10/2014',
        '19/05/2017', '13/02/2016', '12/05/2019', '2/05/2017',
        '13/03/2013', '7/12/2015', '7/10/2014', '14/12/2015', '1/11/2017',
        '14/12/2018', '21/03/2013', '2/11/2010', '14/11/2011',
        '12/08/2013', '10/10/2011', '1/08/2013', '10/09/2016', '1/03/2016',
        '9/08/2017', '17/03/2011', '22/05/2018', '21/09/2015',
        '15/11/2012', '20/02/2017', '9/11/2015', '7/09/2015', '30/03/2016',
        '28/10/2015', '1/08/2016', '5/11/2010', '24/05/2018', '29/05/2013',
        '15/06/2012', '19/10/2011', '12/04/2019', '16/07/2011',
        '13/08/2014', '30/09/2010', '4/07/2019', '11/03/2017',
        '12/09/2012', '3/03/2017', '17/10/2018', '14/05/2014',
        '25/11/2011', '18/02/2015', '1/08/2015', '5/03/2018', '13/02/2017',
        '4/10/2016', '20/09/2012', '14/02/2011', '15/05/2013',
        '22/05/2017', '23/12/2015', '20/12/2018', '1/08/2017', '3/09/2014',
        '19/02/2013', '21/06/2013', '13/04/2017', '20/03/2015',
        '12/05/2015', '4/06/2013', '13/04/2013', '6/06/2018', '4/03/2018',
        '18/10/2016', '19/03/2016', '18/05/2018', '22/03/2018',
        '28/04/2015', '19/02/2018', '22/12/2014', '3/10/2015', '8/07/2011',
        '7/11/2018', '16/06/2012', '5/04/2014', '25/02/2011', '19/06/2017',
        '5/04/2016', '9/08/2013', '9/05/2013', '16/10/2010', '10/02/2016',
        '23/02/2017', '17/03/2018', '4/09/2017', '18/04/2012', '1/07/2013',
        '6/03/2017', '25/09/2015', '13/07/2015', '2/09/2019', '28/02/2017',
        '15/03/2018', '4/10/2010', '25/01/2017', '10/01/2018',
        '18/03/2014', '12/06/2014', '24/05/2012', '2/12/2011', '2/10/2012',
        '3/01/2018', '14/06/2013', '8/11/2014', '10/12/2015', '6/07/2016',
        '5/08/2016', '11/07/2017', '17/04/2013', '17/01/2011',
        '20/07/2018', '12/06/2016', '14/03/2016', '8/10/2019',
        '24/08/2016', '17/07/2013', '17/09/2012', '1/06/2018', '2/07/2011',
        '3/03/2015', '11/01/2017', '17/10/2014', '7/05/2011', '27/11/2012',
        '1/11/2011', '1/06/2014', '1/02/2018', '29/03/2014', '10/08/2018',
        '19/03/2013', '3/09/2013', '24/03/2014', '10/10/2018',
        '11/08/2017', '19/09/2017', '14/11/2019', '12/05/2016',
        '27/05/2014', '23/02/2015', '21/10/2019', '29/08/2012',
        '13/11/2013', '13/06/2014', '13/06/2018', '23/03/2011',
        '6/08/2018', '20/02/2013', '1/09/2011', '4/09/2018', '16/01/2016',
        '26/03/2019', '29/11/2012', '10/07/2012', '24/06/2015',
        '22/03/2011', '16/04/2015', '21/04/2017', '24/03/2015',
        '17/07/2018', '10/08/2011', '21/07/2011', '2/04/2016',
        '28/08/2012', '4/08/2015', '25/02/2014', '9/06/2018', '7/07/2017',
        '29/06/2016', '5/10/2016', '29/04/2014', '2/11/2015', '31/10/2015',
        '14/01/2015', '19/06/2015', '19/04/2017', '1/10/2012',
        '23/09/2015', '15/02/2019', '28/06/2018', '13/02/2014',
        '28/08/2014', '17/06/2013', '11/04/2018', '6/09/2011', '4/02/2011',
        '8/04/2019', '22/01/2019', '19/06/2012', '17/12/2017', '7/11/2019',
        '23/10/2014', '29/06/2012', '31/10/2011', '17/06/2014',
        '13/07/2018', '20/09/2016', '16/11/2011', '20/11/2019',
        '27/10/2011', '12/02/2014', '30/08/2018', '3/06/2013',
        '19/08/2015', '20/10/2010', '5/03/2015', '1/12/2017', '30/06/2011',
        '2/06/2017', '31/10/2012', '12/03/2019', '12/06/2015',
        '21/03/2016', '23/12/2011', '4/07/2012', '23/09/2016', '6/11/2017',
        '20/11/2018', '7/08/2018', '23/08/2012', '6/05/2016', '11/10/2014',
        '3/12/2015', '20/04/2016', '8/02/2016', '3/08/2017', '16/10/2018',
        '26/02/2018', '26/04/2016', '9/07/2011', '9/10/2013', '3/08/2016',
        '19/12/2017', '16/10/2017', '17/06/2015', '1/07/2016',
        '12/04/2012', '18/11/2017', '28/09/2018', '7/02/2012', '9/05/2015',
        '21/08/2017', '7/10/2016', '23/11/2018', '30/11/2011', '2/06/2011',
        '15/08/2015', '26/10/2012', '13/12/2018', '23/07/2015',
        '21/07/2014', '2/03/2011', '6/06/2016', '14/10/2010', '6/12/2011',
        '31/01/2013', '23/09/2012', '24/04/2018', '31/07/2019',
        '27/10/2017', '16/03/2018', '23/09/2014', '30/11/2013',
        '10/06/2014', '25/03/2011', '16/01/2012', '29/08/2013',
        '4/08/2017', '27/06/2015', '25/01/2013', '18/01/2018', '5/12/2014',
        '22/01/2016', '21/10/2017', '19/11/2012', '21/04/2011',
        '31/03/2015', '31/08/2013', '27/06/2011', '18/11/2011',
        '28/08/2018', '1/03/2017', '5/09/2018', '6/04/2017', '26/06/2018',
        '31/05/2016', '24/02/2017', '8/06/2011', '30/10/2016',
        '14/09/2018', '23/11/2014', '20/08/2012', '24/03/2012',
        '21/10/2013', '18/04/2017', '16/05/2019', '5/03/2012', '6/08/2014',
        '13/09/2017', '20/05/2011', '8/07/2015', '5/08/2013', '9/07/2013',
        '29/02/2016', '20/10/2012', '18/07/2012', '3/12/2010',
        '19/01/2015', '7/11/2013', '23/05/2018', '1/05/2017', '21/03/2012',
        '18/08/2016', '30/08/2017', '17/05/2011', '29/01/2018',
        '1/02/2017', '5/04/2013', '8/09/2014', '11/09/2014', '4/02/2019',
        '20/09/2010', '24/10/2011', '23/04/2014', '20/10/2014',
        '27/09/2016', '1/11/2010', '27/07/2016', '15/02/2011',
        '10/03/2018', '13/11/2018', '27/06/2016', '13/07/2017',
        '19/05/2014', '14/02/2015', '6/10/2016', '12/06/2012',
        '27/02/2013', '18/04/2011', '15/09/2014', '15/08/2014',
        '5/12/2016', '13/10/2014', '20/03/2014', '7/08/2015', '2/05/2013',
        '11/04/2017', '18/04/2014', '28/08/2019', '10/10/2013',
        '15/02/2016', '7/10/2015', '20/12/2011', '2/09/2016', '16/05/2012',
        '8/02/2012', '28/04/2012', '27/05/2013', '6/04/2018', '20/11/2015',
        '17/12/2016', '6/01/2014', '4/05/2013', '21/06/2016', '6/07/2017',
        '1/11/2016', '17/04/2018', '2/07/2014', '25/09/2012', '9/09/2015',
        '25/07/2019', '4/10/2012', '13/08/2016', '23/11/2015',
        '22/03/2012', '25/01/2018', '19/09/2018', '15/05/2014',
        '10/04/2017', '6/02/2015', '7/05/2014', '3/11/2017', '6/09/2016',
        '30/08/2013', '6/03/2014', '22/06/2018', '7/04/2014', '23/06/2011',
        '16/10/2015', '21/05/2018', '29/08/2017', '7/10/2018',
        '19/02/2016', '10/07/2013', '4/09/2019', '27/04/2012',
        '19/02/2014', '9/12/2013', '1/10/2019', '2/06/2013', '14/01/2016',
        '26/02/2016', '25/06/2014', '3/05/2013', '7/10/2019', '9/12/2015',
        '2/02/2015', '9/12/2016', '22/04/2014', '24/06/2013', '9/11/2013',
        '31/05/2014', '28/05/2016', '17/02/2013', '3/03/2014', '2/11/2011',
        '12/10/2012', '11/09/2017', '15/11/2019', '17/03/2019',
        '19/07/2017', '2/10/2018', '19/10/2015', '15/06/2018',
        '21/10/2014', '20/05/2019', '29/05/2012', '30/10/2015',
        '22/11/2016', '15/05/2017', '15/07/2015', '2/10/2017',
        '21/01/2012', '10/08/2015', '13/11/2014', '23/10/2012',
        '31/07/2014', '22/12/2016', '4/07/2017', '17/11/2011',
        '26/08/2014', '11/07/2014', '13/10/2016', '6/02/2014',
        '28/03/2014', '26/02/2013', '8/07/2019', '8/09/2013', '1/01/2018',
        '23/09/2019', '6/06/2013', '6/10/2010', '22/09/2014', '16/12/2015',
        '12/01/2019', '22/02/2013', '14/12/2013', '31/05/2018',
        '9/05/2012', '12/06/2013', '29/08/2019', '30/04/2019',
        '25/09/2014', '11/12/2012', '11/06/2013', '14/09/2016',
        '21/08/2019', '20/01/2014', '10/11/2014', '30/01/2017',
        '6/04/2016', '24/02/2015', '20/07/2012', '7/03/2011', '27/02/2018',
        '15/09/2016', '16/07/2014', '7/09/2011', '7/12/2017', '1/12/2016',
        '26/09/2013', '11/05/2011', '7/04/2016', '12/09/2018', '1/03/2019',
        '17/06/2017', '30/05/2019', '10/05/2017', '21/10/2015',
        '13/04/2016', '10/10/2015', '12/10/2011', '29/09/2016',
        '26/12/2017', '10/01/2012', '1/05/2012', '22/01/2015',
        '18/06/2018', '10/10/2014', '3/11/2011', '13/10/2012',
        '22/03/2015', '19/11/2013', '12/11/2015', '17/08/2011',
        '24/09/2019', '22/10/2014', '15/02/2018', '16/03/2014',
        '28/02/2015', '29/07/2012', '16/08/2016', '30/08/2016',
        '2/09/2013', '22/09/2017', '30/09/2019', '25/08/2018',
        '27/09/2012', '23/05/2014', '22/07/2019', '21/02/2011',
        '24/05/2016', '29/12/2012', '29/08/2014', '1/12/2011',
        '30/06/2017', '18/12/2015', '17/06/2019', '14/10/2015',
        '19/03/2018', '8/11/2018', '6/10/2014', '12/11/2013', '18/05/2014',
        '8/04/2015', '24/02/2012', '28/09/2017', '24/10/2018', '9/05/2017',
        '18/08/2018', '12/04/2018', '4/06/2012', '4/07/2015', '17/02/2012',
        '15/07/2011', '9/09/2019', '14/11/2013', '26/09/2011', '2/01/2013',
        '5/02/2013', '1/07/2012', '10/12/2012', '19/03/2011', '13/01/2016',
        '14/12/2011', '19/01/2016', '15/04/2016', '22/04/2017',
        '18/05/2011', '22/06/2017', '2/05/2016', '25/05/2011',
        '29/05/2016', '16/04/2019', '6/04/2014', '17/10/2013',
        '12/11/2010', '27/06/2014', '8/04/2014', '28/04/2016',
        '30/12/2011', '3/08/2013', '10/08/2019', '10/07/2017', '6/12/2014',
        '4/10/2019', '15/05/2012', '31/01/2018', '21/12/2011',
        '29/10/2018', '19/12/2016', '15/11/2011', '23/05/2016',
        '18/02/2014', '9/06/2014', '6/09/2017', '13/08/2017', '12/05/2014',
        '26/11/2018', '7/11/2017', '16/06/2011', '12/04/2017',
        '28/05/2012', '21/10/2011', '30/11/2017', '23/10/2018',
        '19/05/2016', '3/11/2016', '9/03/2013', '8/10/2013', '6/12/2013',
        '19/07/2018', '11/04/2011', '18/05/2016', '1/09/2018',
        '28/02/2013', '5/05/2018', '25/05/2018', '2/05/2014', '17/07/2012',
        '17/10/2012', '7/04/2011', '14/08/2017', '19/06/2019', '5/10/2010',
        '10/12/2014', '3/07/2018', '3/10/2011', '29/01/2014', '2/03/2013',
        '21/08/2013', '12/11/2018', '2/06/2014', '21/12/2016',
        '12/01/2016', '3/04/2019', '19/09/2014', '18/01/2013',
        '28/11/2016', '2/08/2012', '18/05/2013', '24/10/2019', '9/04/2011',
        '15/03/2013', '7/08/2012', '2/04/2011', '8/11/2016', '3/03/2018',
        '17/10/2015', '4/12/2013', '12/07/2012', '17/05/2014',
        '26/07/2017', '3/11/2014', '30/03/2013', '16/05/2015',
        '12/08/2017', '9/10/2019', '4/03/2015', '27/08/2011', '8/01/2019',
        '13/05/2013', '13/01/2014', '25/07/2014', '6/12/2010', '3/12/2016',
        '17/03/2015', '27/03/2017', '24/05/2017', '24/12/2010',
        '30/04/2018', '17/01/2017', '8/06/2014', '20/01/2015',
        '28/08/2015', '14/09/2011', '16/06/2018', '4/02/2013',
        '12/04/2013', '9/12/2014', '7/06/2014', '10/12/2010', '21/10/2010',
        '18/06/2019', '27/11/2014', '30/09/2014', '16/12/2016',
        '17/02/2016', '15/12/2017', '17/09/2011', '17/05/2016',
        '7/08/2013', '26/06/2013', '29/07/2016', '7/05/2013', '8/12/2013',
        '30/09/2017', '4/12/2015', '7/01/2013', '25/05/2015', '8/11/2010',
        '29/11/2017', '23/08/2019', '22/04/2016', '2/10/2015',
        '29/10/2015', '29/04/2011', '25/05/2012', '18/09/2013',
        '15/10/2016', '5/05/2013', '15/12/2010', '11/02/2014', '9/04/2014',
        '11/10/2018', '13/01/2015', '17/09/2010', '3/05/2018',
        '13/10/2010', '8/02/2011', '16/10/2019', '2/10/2010', '5/06/2013',
        '16/06/2015', '28/06/2013', '5/03/2011', '11/10/2015',
        '27/11/2015', '8/07/2016', '3/07/2012', '4/02/2012', '3/04/2017',
        '29/01/2015', '23/03/2015', '11/05/2015', '14/05/2019',
        '6/12/2019', '3/03/2011', '20/06/2015', '24/07/2014', '21/04/2012',
        '9/03/2016', '3/05/2011', '6/08/2012', '23/08/2014', '20/04/2012',
        '5/12/2015', '14/10/2019', '8/02/2018', '28/03/2018', '2/12/2016',
        '29/06/2013', '13/09/2010', '5/02/2016', '3/09/2016', '12/02/2013',
        '17/05/2012', '30/06/2014', '24/08/2019', '2/03/2017', '7/05/2015',
        '29/04/2018', '28/07/2014', '19/06/2018', '22/05/2013',
        '16/12/2011', '19/04/2011', '1/02/2012', '1/02/2016', '7/03/2018',
        '16/11/2016', '31/01/2015', '16/02/2016', '21/09/2011',
        '9/03/2017', '29/09/2010', '5/08/2011', '28/06/2017', '17/03/2014',
        '8/05/2017', '23/09/2017', '8/04/2016', '12/10/2014', '9/10/2017',
        '30/07/2016', '28/10/2016', '21/07/2015', '22/08/2016',
        '23/11/2010', '25/05/2014', '24/08/2013', '11/09/2010',
        '3/02/2016', '13/08/2013', '27/02/2016', '28/03/2017',
        '12/08/2016', '27/07/2012', '25/05/2017', '23/08/2011',
        '5/03/2013', '15/08/2017', '25/10/2011', '27/11/2013', '9/08/2019',
        '23/03/2018', '30/11/2019', '1/07/2011', '3/02/2012', '6/05/2013',
        '26/05/2017', '23/11/2013', '29/07/2015', '13/07/2014',
        '28/11/2012', '26/08/2011', '5/04/2018', '21/11/2011',
        '15/03/2012'], dtype=object),
 'Cl_Dining_Rooms': array([nan,  1.]),
 'Cl_History_From': array(['16/04/2013', '16/12/2014', '26/05/2011', '29/08/2013',
        '7/09/2011', '13/02/2013', '7/12/2011', '9/10/2010', '14/02/2017',
        '21/11/2015', '22/10/2011', '31/05/2015', '21/10/2016',
        '22/08/2018', '28/02/2012', '3/02/2017', '25/03/2011', '4/05/2017',
        '8/08/2016', '26/03/2013', '11/06/2015', '16/03/2011',
        '10/06/2015', '30/08/2013', '11/12/2010', '6/03/2012',
        '16/10/2014', '23/04/2018', '10/06/2011', '21/06/2017',
        '16/06/2017', '15/10/2012', '27/08/2019', '16/12/2015',
        '10/08/2017', '12/10/2017', '13/12/2012', '30/05/2015',
        '6/04/2011', '25/01/2012', '24/09/2014', '6/06/2015', '5/04/2012',
        '19/08/2017', '7/10/2014', '27/07/2016', '13/02/2016', '7/03/2019',
        '2/05/2017', '13/03/2013', '7/12/2015', '14/12/2015', '25/08/2017',
        '14/12/2018', '26/02/2013', '14/10/2010', '14/11/2011',
        '12/08/2013', '10/10/2011', '1/08/2013', '10/09/2016', '1/03/2016',
        '9/08/2017', '17/03/2011', '25/01/2018', '17/09/2015',
        '15/11/2012', '9/11/2015', '15/02/2012', '30/03/2016',
        '28/10/2015', '5/11/2010', '24/05/2018', '6/05/2013', '19/10/2011',
        '27/12/2018', '14/07/2011', '9/08/2014', '30/09/2010',
        '23/02/2019', '11/03/2017', '12/09/2012', '30/11/2015',
        '17/10/2018', '5/05/2014', '25/11/2011', '11/02/2015', '1/08/2015',
        '18/10/2017', '13/02/2017', '4/10/2016', '20/09/2012',
        '14/02/2011', '7/05/2013', '19/03/2017', '17/12/2015',
        '29/11/2018', '1/08/2017', '31/08/2014', '19/02/2013',
        '21/06/2013', '29/04/2014', '20/03/2015', '12/05/2015',
        '4/06/2013', '13/04/2013', '9/03/2017', '4/03/2018', '16/03/2016',
        '17/04/2018', '4/11/2017', '28/04/2015', '19/02/2018',
        '22/12/2014', '3/10/2015', '8/07/2011', '7/11/2018', '16/06/2012',
        '5/04/2014', '25/02/2011', '19/06/2017', '5/04/2016', '9/08/2013',
        '13/04/2012', '16/10/2010', '10/02/2016', '23/02/2017',
        '17/03/2018', '4/09/2017', '4/11/2011', '1/07/2013', '6/03/2017',
        '25/09/2015', '13/07/2015', '12/07/2019', '15/03/2018',
        '24/08/2010', '11/01/2017', '10/01/2018', '3/09/2014',
        '18/03/2014', '12/06/2014', '24/05/2012', '2/12/2011', '2/10/2012',
        '3/11/2017', '14/06/2013', '8/11/2014', '14/03/2019', '7/06/2015',
        '9/10/2014', '5/08/2016', '11/07/2017', '20/03/2013', '17/04/2013',
        '17/01/2011', '20/07/2018', '12/06/2016', '7/11/2015', '1/05/2019',
        '24/08/2016', '16/07/2013', '17/09/2012', '1/06/2018', '2/07/2011',
        '3/03/2015', '6/12/2016', '17/10/2014', '7/03/2011', '27/11/2012',
        '5/10/2011', '1/06/2014', '2/12/2017', '22/10/2013', '29/03/2014',
        '19/03/2013', '3/09/2013', '24/03/2014', '10/10/2018',
        '19/07/2017', '14/03/2016', '19/09/2017', '14/11/2019',
        '10/05/2016', '27/05/2014', '23/02/2015', '21/10/2019',
        '29/08/2012', '13/11/2013', '8/02/2013', '23/03/2011', '6/08/2018',
        '1/09/2011', '4/09/2018', '16/01/2016', '29/11/2012', '10/07/2012',
        '24/06/2015', '22/03/2011', '16/04/2015', '21/04/2017',
        '24/03/2015', '17/07/2018', '10/08/2011', '21/07/2011',
        '2/04/2016', '28/08/2012', '4/08/2015', '25/02/2014', '9/06/2018',
        '7/07/2017', '29/06/2016', '4/09/2011', '2/11/2015', '31/10/2015',
        '14/01/2015', '19/06/2015', '19/04/2017', '25/07/2012',
        '23/09/2015', '15/02/2019', '31/08/2011', '3/10/2017',
        '15/11/2013', '28/08/2014', '17/06/2013', '29/03/2017',
        '6/09/2011', '4/02/2011', '8/04/2019', '17/01/2019', '8/03/2012',
        '17/12/2017', '1/02/2019', '23/10/2014', '29/06/2012', '3/04/2011',
        '17/06/2014', '22/03/2018', '20/09/2016', '5/11/2019',
        '27/10/2011', '12/02/2014', '30/08/2018', '3/06/2013',
        '19/08/2015', '18/09/2010', '5/03/2015', '1/12/2017', '30/06/2011',
        '10/04/2017', '31/10/2012', '12/03/2019', '12/06/2015',
        '1/11/2015', '13/12/2011', '4/07/2012', '16/02/2012', '5/11/2018',
        '7/08/2018', '23/08/2012', '28/04/2016', '11/10/2014',
        '20/04/2016', '8/02/2016', '3/08/2017', '16/10/2018', '16/02/2018',
        '26/04/2016', '9/07/2011', '3/08/2016', '19/12/2017', '16/10/2017',
        '1/07/2016', '12/04/2012', '14/03/2018', '28/10/2017', '7/02/2012',
        '9/05/2015', '21/08/2017', '7/10/2016', '23/11/2018', '30/11/2011',
        '2/06/2011', '15/08/2015', '26/10/2012', '3/10/2018', '23/07/2015',
        '21/07/2014', '2/03/2011', '5/04/2015', '6/12/2011', '21/12/2012',
        '23/09/2012', '24/04/2018', '13/12/2010', '31/07/2019',
        '27/10/2017', '9/10/2017', '23/09/2014', '4/11/2013', '1/05/2014',
        '16/01/2012', '4/08/2017', '13/06/2013', '25/01/2013',
        '18/01/2018', '5/12/2014', '22/01/2016', '21/10/2017', '2/04/2017',
        '19/11/2012', '21/04/2011', '31/03/2015', '31/08/2013',
        '11/04/2011', '18/11/2011', '27/07/2018', '1/03/2017', '5/09/2018',
        '26/06/2018', '31/05/2016', '24/02/2017', '8/06/2011',
        '30/10/2016', '14/09/2018', '23/11/2014', '27/07/2012',
        '24/03/2012', '3/03/2017', '21/10/2013', '18/04/2017',
        '16/05/2019', '6/08/2014', '13/09/2017', '20/05/2011', '8/07/2015',
        '2/08/2013', '9/07/2013', '29/02/2016', '12/10/2012', '18/07/2012',
        '3/12/2010', '19/01/2015', '3/11/2013', '23/05/2018', '9/12/2015',
        '1/05/2017', '3/05/2013', '24/01/2012', '18/08/2016', '29/08/2017',
        '17/05/2011', '29/01/2018', '1/02/2017', '25/03/2013', '8/09/2014',
        '9/12/2013', '10/09/2010', '24/10/2011', '23/04/2014',
        '20/10/2014', '27/09/2016', '29/08/2010', '6/02/2011',
        '10/03/2018', '29/10/2018', '27/06/2016', '13/07/2017',
        '14/02/2015', '6/10/2016', '6/06/2012', '19/01/2013', '20/12/2010',
        '15/09/2014', '20/01/2013', '15/08/2014', '5/12/2016',
        '25/08/2014', '21/02/2014', '7/08/2015', '2/05/2013', '11/04/2017',
        '18/04/2014', '2/08/2017', '3/10/2013', '15/02/2016', '7/10/2015',
        '20/12/2011', '6/09/2018', '2/09/2016', '16/05/2012', '8/02/2012',
        '28/04/2012', '9/03/2013', '6/04/2018', '20/11/2015', '17/12/2016',
        '6/01/2014', '9/04/2013', '21/06/2016', '23/09/2013', '6/07/2017',
        '1/11/2016', '2/07/2014', '25/09/2012', '23/01/2018', '9/09/2015',
        '4/10/2012', '13/08/2016', '5/11/2015', '22/03/2012', '15/05/2014',
        '6/02/2015', '7/05/2014', '21/09/2017', '6/09/2016', '20/01/2014',

In [229]:
t = tr.FunctionTransformer(ex.get_distinct_value, 'Cl_Toilets')
t.fit_transform(sdf)

{'Cl_Toilets': array([nan,  1.,  2.,  3.,  4.,  5.])}

In [228]:
t = tr.FunctionTransformer(ex.get_distinct_value, 'Cl_Toilets', 'Cl_Scenic_View')
t.fit_transform(sdf)

{'Cl_Toilets': array([nan,  1.,  2.,  3.,  4.,  5.]),
 'Cl_Scenic_View': array([nan, 'Y'], dtype=object)}

### Transform Debugger

In [239]:
reload(tr)

In [242]:
reload(ut)

In [248]:
imputer = tr.ConstantImputer()

In [251]:
imputer.fit_transform(df)

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
0,9160056.0,440000.0,16/04/2013,16/04/2013,1045.0,0.0,0.0,3,2,0.0,...,missing_value,10,0.0,Marian,Street,missing_value,Aireys Inlet,3231.0,VIC,930.0
1,17246721.0,355250.0,16/12/2014,16/12/2014,0.0,0.0,0.0,missing_value,missing_value,0.0,...,missing_value,11,0.0,Bowral,Grove,missing_value,Jordan Springs,2747.0,NSW,425.0
2,12087127.0,285000.0,25/09/2011,26/05/2011,550.0,0.0,85.0,3,1,1.0,...,missing_value,3B,0.0,Beckford,Close,missing_value,East Cannington,6107.0,WA,550.0
3,5803664.0,687000.0,6/09/2013,29/08/2013,3051.0,0.0,82.0,2,1,1.0,...,missing_value,41,0.0,Pitt,Street,missing_value,Redfern,2016.0,NSW,3050.0
4,6828541.0,280000.0,15/10/2011,7/09/2011,645.0,0.0,0.0,3,1,2.0,...,missing_value,58,0.0,Beeville,Road,missing_value,Petrie,4502.0,QLD,645.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,14934488.0,600000.0,26/08/2011,26/08/2011,0.0,0.0,0.0,2,2,0.0,...,missing_value,63,0.0,Whiteman,Street,missing_value,Southbank,3006.0,VIC,0.0
996,9763002.0,375000.0,5/04/2018,5/04/2018,914.0,0.0,0.0,2,1,1.0,...,missing_value,215,0.0,Grey,Street,West,Albany,6330.0,WA,913.0
997,3315707.0,370000.0,21/11/2011,21/11/2011,1204.0,0.0,92.0,2,1,1.0,...,missing_value,30,0.0,Chelsea,Avenue,missing_value,Broadbeach,4218.0,QLD,0.0
998,17508144.0,127500.0,8/07/2016,8/07/2016,719.0,0.0,195.0,4,2,2.0,...,missing_value,6,0.0,Obrien,Circuit,missing_value,North Wonthaggi,3995.0,VIC,719.0
999,12946849.0,21150.0,15/03/2012,15/03/2012,894.0,0.0,0.0,3,1,0.0,...,missing_value,82,0.0,Gairdner,Street,missing_value,Northam,6401.0,WA,850.0

In [252]:
len(df)

1000

In [255]:
import random
random.randrange(0, 1000)

516

In [261]:
t = tr.TransformDebugger(imputer, ut.show_row)

In [262]:
t.fit_transform(df)

ConstantImputer
Before ========================================
Cl_Property_ID                         2662206
CL_Contract_Price                       845000
CL_Transfer_Date                    16/05/2015
Cl_History_From                     16/05/2015
Cl_Est_Land_Area                           588
Cl_Equiv_Building_Area                     NaN
Cl_Floor_Area                              NaN
Cl_Bedrooms                                  5
Cl_Bathrooms                                 1
Cl_Car_Spaces                                1
Cl_Garages                                   2
Cl_Year_Built                              NaN
Cl_Materials_In_Roof                       NaN
Cl_Materials_In_External_Walls             NaN
Cl_Materials_In_Floor             Timber Floor
Cl_Bond_Amount                             NaN
Cl_Access_Security_Installed               NaN
Cl_Air_Conditioned                           Y
Cl_Architectural_Style                     NaN
Cl_Close_To_Public_Transport               NaN
Cl_Condition                               NaN
Cl_Construction_Type                       NaN
Cl_Dining_Rooms                              1
Cl_Ensuites                                NaN
Cl_Family_Rooms                              1
Cl_Fireplace                               NaN
Cl_Floor_Level_Of_Unit                     NaN
Cl_Frontage                                NaN
Cl_Lounge_Rooms                              1
Cl_Street_Frontage_Size                    NaN
Cl_Games_Rooms                             NaN
Cl_Kitchens                                NaN
Cl_Meal_Rooms                              NaN
Cl_Study_Rooms                               1
Cl_Floor_Levels_Inside_Unit                NaN
Cl_On_Main_Road                            NaN
Cl_Renovated                               NaN
Cl_Scenic_View                             NaN
Cl_Swimming_Pool                           NaN
Cl_Toilets                                   1
Cl_Heritage_Flag                           NaN
CL_Property_Type                         House
CL_Unit_No                                 NaN
CL_Unit_No_Derived                         NaN
CL_Street_No_Start                          19
CL_Street_No_End                           NaN
CL_Street_Name                          Lester
CL_Street_Type                            Road
CL_Street_Direction                        NaN
CL_Suburb                           Greystanes
CL_Postcode                               2145
CL_State                                   NSW
CL_Land_Area                               588
Name: 792, dtype: object
After ========================================
Cl_Property_ID                      2.66221e+06
CL_Contract_Price                        845000
CL_Transfer_Date                     16/05/2015
Cl_History_From                      16/05/2015
Cl_Est_Land_Area                            588
Cl_Equiv_Building_Area                        0
Cl_Floor_Area                                 0
Cl_Bedrooms                                   5
Cl_Bathrooms                                  1
Cl_Car_Spaces                                 1
Cl_Garages                                    2
Cl_Year_Built                                 0
Cl_Materials_In_Roof              missing_value
Cl_Materials_In_External_Walls    missing_value
Cl_Materials_In_Floor              Timber Floor
Cl_Bond_Amount                                0
Cl_Access_Security_Installed      missing_value
Cl_Air_Conditioned                            Y
Cl_Architectural_Style            missing_value
Cl_Close_To_Public_Transport      missing_value
Cl_Condition                      missing_value
Cl_Construction_Type              missing_value
Cl_Dining_Rooms                               1
Cl_Ensuites                       missing_value
Cl_Family_Rooms                               1
Cl_Fireplace                      missing_value
Cl_Floor_Level_Of_Unit            missing_value
Cl_Frontage                                   0
Cl_Lounge_Rooms                               1
Cl_Street_Frontage_Size                       0
Cl_Games_Rooms                    missing_value
Cl_Kitchens                       missing_value
Cl_Meal_Rooms                     missing_value
Cl_Study_Rooms                                1
Cl_Floor_Levels_Inside_Unit       missing_value
Cl_On_Main_Road                   missing_value
Cl_Renovated                      missing_value
Cl_Scenic_View                    missing_value
Cl_Swimming_Pool                  missing_value
Cl_Toilets                                    1
Cl_Heritage_Flag                  missing_value
CL_Property_Type                          House
CL_Unit_No                        missing_value
CL_Unit_No_Derived                missing_value
CL_Street_No_Start                           19
CL_Street_No_End                              0
CL_Street_Name                           Lester
CL_Street_Type                             Road
CL_Street_Direction               missing_value
CL_Suburb                            Greystanes
CL_Postcode                                2145
CL_State                                    NSW
CL_Land_Area                                588
Name: 792, dtype: object

,Cl_Property_ID,CL_Contract_Price,CL_Transfer_Date,Cl_History_From,Cl_Est_Land_Area,Cl_Equiv_Building_Area,Cl_Floor_Area,Cl_Bedrooms,Cl_Bathrooms,Cl_Car_Spaces,...,CL_Unit_No_Derived,CL_Street_No_Start,CL_Street_No_End,CL_Street_Name,CL_Street_Type,CL_Street_Direction,CL_Suburb,CL_Postcode,CL_State,CL_Land_Area
0,9160056,440000.0,16/04/2013,16/04/2013,1045.0,NaN,NaN,3.0,2.0,NaN,...,NaN,10,NaN,Marian,Street,NaN,Aireys Inlet,3231,VIC,930.0
1,17246721,355250.0,16/12/2014,16/12/2014,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11,NaN,Bowral,Grove,NaN,Jordan Springs,2747,NSW,425.0
2,12087127,285000.0,25/09/2011,26/05/2011,550.0,NaN,85.0,3.0,1.0,1.0,...,NaN,3B,NaN,Beckford,Close,NaN,East Cannington,6107,WA,550.0
3,5803664,687000.0,6/09/2013,29/08/2013,3051.0,NaN,82.0,2.0,1.0,1.0,...,NaN,41,NaN,Pitt,Street,NaN,Redfern,2016,NSW,3050.0
4,6828541,280000.0,15/10/2011,7/09/2011,645.0,NaN,NaN,3.0,1.0,2.0,...,NaN,58,NaN,Beeville,Road,NaN,Petrie,4502,QLD,645.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,14934488,600000.0,26/08/2011,26/08/2011,NaN,NaN,NaN,2.0,2.0,NaN,...,NaN,63,NaN,Whiteman,Street,NaN,Southbank,3006,VIC,NaN
996,9763002,375000.0,5/04/2018,5/04/2018,914.0,NaN,NaN,2.0,1.0,1.0,...,NaN,215,NaN,Grey,Street,West,Albany,6330,WA,913.0
997,3315707,370000.0,21/11/2011,21/11/2011,1204.0,NaN,92.0,2.0,1.0,1.0,...,NaN,30,NaN,Chelsea,Avenue,NaN,Broadbeach,4218,QLD,NaN
998,17508144,127500.0,8/07/2016,8/07/2016,719.0,NaN,195.0,4.0,2.0,2.0,...,NaN,6,NaN,Obrien,Circuit,NaN,North Wonthaggi,3995,VIC,719.0
999,12946849,21150.0,15/03/2012,15/03/2012,894.0,NaN,NaN,3.0,1.0,NaN,...,NaN,82,NaN,Gairdner,Street,NaN,Northam,6401,WA,850.0

In [6]:
from sklearn.pipeline import Pipeline

### Pipleline

In [28]:
pipeline = Pipeline([
     ('Value Remover', tr.ValueRemover(['sex'], ['F'])),
])

In [31]:
sdf = pipeline.fit_transform(df)

In [32]:
sdf.shape

(2870, 9)

In [35]:
from imp import reload

In [40]:
ex.count_levels(sdf)

{'sex': [('I', 1342), ('M', 1528)],
 'length': [(0.075, 1),
  (0.11, 1),
  (0.13, 2),
  (0.135, 1),
  (0.14, 2),
  (0.15, 1),
  (0.155, 3),
  (0.16, 4),
  (0.165, 5),
  (0.17, 3),
  (0.175, 5),
  (0.18, 4),
  (0.185, 4),
  (0.19, 4),
  (0.195, 3),
  (0.2, 6),
  (0.205, 5),
  (0.21, 6),
  (0.215, 5),
  (0.22, 2),
  (0.225, 4),
  (0.23, 4),
  (0.235, 10),
  (0.24, 7),
  (0.245, 6),
  (0.25, 8),
  (0.255, 13),
  (0.26, 5),
  (0.265, 6),
  (0.27, 11),
  (0.275, 18),
  (0.28, 18),
  (0.285, 9),
  (0.29, 11),
  (0.295, 14),
  (0.3, 14),
  (0.305, 5),
  (0.31, 15),
  (0.315, 16),
  (0.32, 18),
  (0.325, 17),
  (0.33, 21),
  (0.335, 21),
  (0.34, 14),
  (0.345, 12),
  (0.35, 30),
  (0.355, 20),
  (0.36, 30),
  (0.365, 19),
  (0.37, 31),
  (0.375, 36),
  (0.38, 20),
  (0.385, 30),
  (0.39, 20),
  (0.395, 20),
  (0.4, 26),
  (0.405, 21),
  (0.41, 26),
  (0.415, 31),
  (0.42, 27),
  (0.425, 33),
  (0.43, 26),
  (0.435, 31),
  (0.44, 43),
  (0.445, 24),
  (0.45, 46),
  (0.455, 32),
  (0.46, 39),
  (0.465, 35),
  (0.47, 43),
  (0.475, 50),
  (0.48, 32),
  (0.485, 39),
  (0.49, 26),
  (0.495, 34),
  (0.5, 61),
  (0.505, 35),
  (0.51, 33),
  (0.515, 46),
  (0.52, 50),
  (0.525, 50),
  (0.53, 48),
  (0.535, 39),
  (0.54, 34),
  (0.545, 36),
  (0.55, 63),
  (0.555, 37),
  (0.56, 43),
  (0.565, 41),
  (0.57, 47),
  (0.575, 60),
  (0.58, 52),
  (0.585, 36),
  (0.59, 51),
  (0.595, 34),
  (0.6, 52),
  (0.605, 34),
  (0.61, 42),
  (0.615, 37),
  (0.62, 48),
  (0.625, 51),
  (0.63, 51),
  (0.635, 31),
  (0.64, 28),
  (0.645, 36),
  (0.65, 42),
  (0.655, 22),
  (0.66, 24),
  (0.665, 16),
  (0.67, 22),
  (0.675, 11),
  (0.68, 14),
  (0.685, 12),
  (0.69, 11),
  (0.695, 16),
  (0.7, 15),
  (0.705, 5),
  (0.71, 10),
  (0.715, 7),
  (0.72, 14),
  (0.725, 7),
  (0.73, 3),
  (0.735, 7),
  (0.74, 5),
  (0.745, 3),
  (0.75, 3),
  (0.755, 1),
  (0.76, 2),
  (0.765, 2),
  (0.77, 3),
  (0.775, 2),
  (0.78, 1)],
 'diameter': [(0.055, 1),
  (0.09, 1),
  (0.095, 1),
  (0.1, 2),
  (0.105, 4),
  (0.11, 4),
  (0.115, 2),
  (0.12, 5),
  (0.125, 7),
  (0.13, 8),
  (0.135, 5),
  (0.14, 3),
  (0.145, 5),
  (0.15, 11),
  (0.155, 4),
  (0.16, 4),
  (0.165, 4),
  (0.17, 8),
  (0.175, 11),
  (0.18, 10),
  (0.185, 8),
  (0.19, 10),
  (0.195, 14),
  (0.2, 17),
  (0.205, 18),
  (0.21, 17),
  (0.215, 18),
  (0.22, 14),
  (0.225, 17),
  (0.23, 20),
  (0.235, 17),
  (0.24, 19),
  (0.245, 13),
  (0.25, 28),
  (0.255, 23),
  (0.26, 24),
  (0.265, 34),
  (0.27, 35),
  (0.275, 32),
  (0.28, 41),
  (0.285, 22),
  (0.29, 34),
  (0.295, 15),
  (0.3, 43),
  (0.305, 25),
  (0.31, 37),
  (0.315, 26),
  (0.32, 24),
  (0.325, 49),
  (0.33, 30),
  (0.335, 37),
  (0.34, 40),
  (0.345, 40),
  (0.35, 55),
  (0.355, 58),
  (0.36, 37),
  (0.365, 37),
  (0.37, 45),
  (0.375, 58),
  (0.38, 53),
  (0.385, 49),
  (0.39, 45),
  (0.395, 40),
  (0.4, 78),
  (0.405, 48),
  (0.41, 42),
  (0.415, 38),
  (0.42, 60),
  (0.425, 52),
  (0.43, 44),
  (0.435, 53),
  (0.44, 53),
  (0.445, 36),
  (0.45, 90),
  (0.455, 56),
  (0.46, 51),
  (0.465, 43),
  (0.47, 69),
  (0.475, 64),
  (0.48, 52),
  (0.485, 41),
  (0.49, 49),
  (0.495, 37),
  (0.5, 46),
  (0.505, 35),
  (0.51, 41),
  (0.515, 42),
  (0.52, 28),
  (0.525, 46),
  (0.53, 20),
  (0.535, 13),
  (0.54, 15),
  (0.545, 12),
  (0.55, 23),
  (0.555, 7),
  (0.56, 7),
  (0.565, 13),
  (0.57, 10),
  (0.575, 9),
  (0.58, 6),
  (0.585, 6),
  (0.59, 4),
  (0.595, 3),
  (0.6, 5),
  (0.605, 3),
  (0.62, 1),
  (0.63, 1)],
 'height': [(0.0, 2),
  (0.01, 1),
  (0.015, 1),
  (0.02, 2),
  (0.025, 5),
  (0.03, 6),
  (0.035, 6),
  (0.04, 13),
  (0.045, 11),
  (0.05, 18),
  (0.055, 25),
  (0.06, 26),
  (0.065, 38),
  (0.07, 44),
  (0.075, 59),
  (0.08, 72),
  (0.085, 72),
  (0.09, 115),
  (0.095, 87),
  (0.1, 133),
  (0.105, 90),
  (0.11, 110),
  (0.115, 89),
  (0.12, 134),
  (0.125, 151),
  (0.13, 127),
  (0.135, 127),
  (0.14, 152),
  (0.145, 127),
  (0.15, 154),
  (0.155, 135),
  (0.16, 114),
  (0.165, 103),
  (0.17, 74),
  (0.175, 115),
  (0.18, 69),
  (0.185, 58),
  (0.19, 53),
  (0.195, 38),
  (0.2, 38),
  (0.205, 20),
  (0.21, 10),
  (0.215, 18),
  (0.22, 8),
  (0.225, 5),
  (0.23, 7),
  (0.235, 3),
  (0.24, 3),
  (0.25, 1),
  (0.515, 1)],
 'whole_wt': [(0.002, 1),
  (0.008, 1),
  (0.0105, 1),
  (0.013000000000000001, 1),
  (0.013999999999999999, 1),
  (0.0145, 2),
  (0.015, 1),
  (0.0155, 1),
  (0.0175, 1),
  (0.018000000000000002, 2),
  (0.019, 1),
  (0.0195, 1),
  (0.021, 2),
  (0.0215, 1),
  (0.023, 1),
  (0.0235, 2),
  (0.024, 2),
  (0.0245, 1),
  (0.0265, 2),
  (0.027000000000000003, 1),
  (0.0275, 1),
  (0.027999999999999997, 1),
  (0.028999999999999998, 2),
  (0.0295, 1),
  (0.03, 1),
  (0.0305, 1),
  (0.0315, 2),
  (0.032, 2),
  (0.0325, 1),
  (0.033, 1),
  (0.034, 1),
  (0.0345, 1),
  (0.035, 1),
  (0.036000000000000004, 1),
  (0.037000000000000005, 1),
  (0.0375, 1),
  (0.038, 1),
  (0.0385, 2),
  (0.04, 2),
  (0.040999999999999995, 1),
  (0.042, 2),
  (0.0425, 1),
  (0.0435, 1),
  (0.0455, 1),
  (0.046, 2),
  (0.0465, 2),
  (0.0475, 1),
  (0.048, 1),
  (0.049, 1),
  (0.0495, 1),
  (0.0515, 3),
  (0.0525, 1),
  (0.0545, 3),
  (0.0555, 1),
  (0.0565, 1),
  (0.057, 1),
  (0.057999999999999996, 1),
  (0.059000000000000004, 2),
  (0.0605, 1),
  (0.0615, 1),
  (0.0625, 1),
  (0.0635, 2),
  (0.064, 1),
  (0.0645, 2),
  (0.0655, 1),
  (0.0665, 1),
  (0.067, 1),
  (0.0685, 2),
  (0.07, 1),
  (0.0705, 2),
  (0.071, 2),
  (0.0715, 1),
  (0.0725, 1),
  (0.073, 2),
  (0.0735, 1),
  (0.07400000000000001, 1),
  (0.075, 1),
  (0.0765, 2),
  (0.0785, 1),
  (0.079, 1),
  (0.08, 1),
  (0.0805, 1),
  (0.081, 1),
  (0.0815, 1),
  (0.083, 2),
  (0.0835, 1),
  (0.084, 3),
  (0.086, 3),
  (0.0865, 1),
  (0.0875, 1),
  (0.08800000000000001, 1),
  (0.0895, 1),
  (0.0905, 1),
  (0.0915, 1),
  (0.092, 3),
  (0.0925, 2),
  (0.0935, 1),
  (0.094, 1),
  (0.0945, 1),
  (0.095, 1),
  (0.096, 4),
  (0.0965, 1),
  (0.09699999999999999, 2),
  (0.0975, 2),
  (0.0985, 1),
  (0.099, 3),
  (0.0995, 1),
  (0.1, 3),
  (0.1005, 1),
  (0.10099999999999999, 3),
  (0.1015, 1),
  (0.102, 1),
  (0.1035, 1),
  (0.1045, 1),
  (0.1055, 3),
  (0.106, 5),
  (0.1065, 2),
  (0.1075, 3),
  (0.1085, 1),
  (0.109, 1),
  (0.1105, 2),
  (0.111, 1),
  (0.1115, 2),
  (0.1125, 1),
  (0.1135, 1),
  (0.1145, 2),
  (0.1155, 1),
  (0.11599999999999999, 1),
  (0.1165, 3),
  (0.11699999999999999, 2),
  (0.11800000000000001, 1),
  (0.1185, 2),
  (0.1195, 3),
  (0.12, 1),
  (0.1205, 1),
  (0.121, 2),
  (0.1225, 1),
  (0.1235, 1),
  (0.124, 2),
  (0.1245, 1),
  (0.125, 2),
  (0.1255, 1),
  (0.126, 1),
  (0.127, 4),
  (0.1275, 2),
  (0.128, 1),
  (0.1285, 3),
  (0.129, 2),
  (0.1295, 3),
  (0.131, 2),
  (0.1315, 2),
  (0.132, 1),
  (0.133, 1),
  (0.134, 1),
  (0.1345, 2),
  (0.1365, 2),
  (0.13699999999999998, 1),
  (0.1375, 2),
  (0.1385, 3),
  (0.139, 1),
  (0.14, 1),
  (0.1405, 1),
  (0.141, 1),
  (0.1415, 1),
  (0.1425, 1),
  (0.1435, 1),
  (0.14400000000000002, 2),
  (0.1445, 2),
  (0.1455, 2),
  (0.146, 1),
  (0.1465, 1),
  (0.147, 1),
  (0.1485, 2),
  (0.149, 1),
  (0.1495, 1),
  (0.15, 2),
  (0.151, 2),
  (0.1515, 1),
  (0.152, 3),
  (0.1525, 1),
  (0.1545, 1),
  (0.155, 2),
  (0.1555, 1),
  (0.156, 1),
  (0.1565, 1),
  (0.1575, 1),
  (0.1585, 3),
  (0.1595, 1),
  (0.1605, 1),
  (0.161, 2),
  (0.1625, 1),
  (0.163, 3),
  (0.1635, 1),
  (0.16399999999999998, 1),
  (0.1655, 1),
  (0.166, 1),
  (0.1665, 1),
  (0.16699999999999998, 1),
  (0.168, 2),
  (0.16899999999999998, 1),
  (0.1695, 3),
  (0.17, 3),
  (0.171, 1),
  (0.1715, 2),
  (0.172, 1),
  (0.17300000000000001, 1),
  (0.1735, 3),
  (0.174, 1),
  (0.1745, 2),
  (0.1755, 2),
  (0.17600000000000002, 1),
  (0.1765, 2),
  (0.1775, 2),
  (0.1785, 5),
  (0.179, 3),
  (0.1795, 1),
  (0.18, 6),
  (0.18100000000000002, 2),
  (0.1825, 1),
  (0.183, 3),
  (0.1835, 2),
  (0.1845, 1),
  (0.185, 3),
  (0.1855, 1),
  (0.18600000000000003, 1),
  (0.1865, 1),
  (0.187, 3),
  (0.1875, 2),
  (0.1885, 1),
  (0.1895, 1),
  (0.19, 1),
  (0.1905, 1),
  (0.1915, 1),
  (0.192, 3),
  (0.1925, 1),
  (0.1945, 1),
  (0.195, 2),
  (0.196, 7),
  (0.1965, 2),
  (0.19699999999999998, 4),
  (0.1975, 2),
  (0.198, 2),
  (0.1985, 2),
  (0.19899999999999998, 2),
  (0.1995, 1),
  (0.2, 3),
  (0.2005, 2),
  (0.201, 1),
  (0.2015, 3),
  (0.2025, 1),
  (0.203, 2),
  (0.204, 1),
  (0.2045, 1),
  (0.205, 2),
  (0.2055, 2),
  (0.2065, 2),
  (0.2075, 2),
  (0.2085, 1),
  (0.209, 1),
  (0.2105, 2),
  (0.21100000000000002, 1),
  (0.213, 3),
  (0.2135, 1),
  (0.214, 1),
  (0.2145, 2),
  (0.215, 3),
  (0.2155, 2),
  (0.21600000000000003, 1),
  (0.2165, 1),
  (0.217, 3),
  (0.2175, 2),
  (0.218, 4),
  (0.2185, 1),
  (0.21899999999999997, 3),
  (0.22, 4),
  (0.2205, 2),
  (0.221, 2),
  (0.2215, 3),
  (0.222, 1),
  (0.2225, 7),
  (0.223, 1),
  (0.2235, 2),
  (0.22399999999999998, 1),
  (0.2255, 4),
  (0.226, 3),
  (0.2265, 1),
  (0.2275, 2),
  (0.228, 2),
  (0.2285, 1),
  (0.2295, 2),
  (0.2305, 1),
  (0.2315, 2),
  (0.23199999999999998, 3),
  (0.2325, 2),
  (0.233, 1),
  (0.2335, 1),
  (0.23399999999999999, 1),
  (0.2345, 2),
  (0.2365, 1),
  (0.237, 3),
  (0.23800000000000002, 1),
  (0.2385, 1),
  (0.239, 1),
  (0.24, 2),
  (0.24100000000000002, 2),
  (0.2415, 1),
  (0.2425, 1),
  (0.243, 1),
  (0.2435, 1),
  (0.244, 2),
  (0.2445, 1),
  (0.2455, 2),
  (0.2465, 2),
  (0.247, 1),
  (0.248, 1),
  (0.2485, 1),
  (0.249, 1),
  (0.25, 2),
  (0.2505, 3),
  (0.251, 2),
  (0.252, 4),
  (0.253, 2),
  (0.2535, 1),
  (0.2545, 2),
  (0.2555, 1),
  (0.256, 1),
  (0.2565, 2),
  (0.257, 3),
  (0.2575, 1),
  (0.258, 2),
  (0.259, 1),
  (0.2595, 1),
  (0.2605, 1),
  (0.2615, 1),
  (0.262, 1),
  (0.2625, 2),
  (0.2645, 2),
  (0.2655, 1),
  (0.266, 1),
  (0.2665, 3),
  (0.2675, 2),
  (0.268, 1),
  (0.2685, 1),
  (0.26899999999999996, 1),
  (0.27, 1),
  (0.271, 3),
  (0.2715, 2),
  (0.2725, 1),
  (0.2735, 1),
  (0.2745, 1),
  (0.2755, 1),
  (0.276, 1),
  (0.2765, 1),
  (0.27699999999999997, 1),
  (0.2775, 2),
  (0.27899999999999997, 3),
  (0.2795, 1),
  (0.28, 2),
  (0.2805, 3),
  (0.281, 1),
  (0.2815, 3),
  (0.282, 2),
  (0.2825, 2),
  (0.28300000000000003, 1),
  (0.284, 1),
  (0.2845, 2),
  (0.2855, 1),
  (0.28600000000000003, 1),
  (0.2865, 2),
  (0.287, 1),
  (0.2875, 3),
  (0.2885, 4),
  (0.2895, 1),
  (0.2905, 3),
  (0.2925, 1),
  (0.293, 1),
  (0.2935, 1),
  (0.2965, 2),
  (0.297, 1),
  (0.298, 1),
  (0.2985, 2),
  (0.2995, 1),
  (0.3, 3),
  (0.3005, 1),
  (0.301, 2),
  (0.302, 2),
  (0.3025, 1),
  (0.303, 2),
  (0.3035, 1),
  (0.304, 3),
  (0.3045, 2),
  (0.305, 1),
  (0.3055, 2),
  (0.306, 3),
  (0.3075, 2),
  (0.308, 1),
  (0.3085, 1),
  (0.309, 2),
  (0.3095, 1),
  (0.311, 1),
  (0.312, 2),
  (0.313, 2),
  (0.314, 3),
  (0.315, 2),
  (0.3155, 1),
  (0.316, 3),
  (0.317, 2),
  (0.3175, 1),
  (0.318, 1),
  (0.3185, 1),
  (0.319, 1),
  (0.32, 2),
  (0.3205, 1),
  (0.3215, 2),
  (0.3225, 1),
  (0.324, 1),
  (0.3245, 6),
  (0.325, 2),
  (0.326, 1),
  (0.3265, 3),
  (0.3275, 2),
  (0.32799999999999996, 1),
  (0.3285, 1),
  (0.32899999999999996, 1),
  (0.3295, 2),
  (0.33, 3),
  (0.3305, 1),
  (0.3325, 1),
  (0.3335, 3),
  (0.33399999999999996, 1),
  (0.335, 4),
  (0.3355, 1),
  (0.336, 2),
  (0.33899999999999997, 1),
  (0.34, 3),
  (0.3405, 1),
  (0.3415, 2),
  (0.342, 1),
  (0.3425, 1),
  (0.34299999999999997, 1),
  (0.3435, 3),
  (0.344, 2),
  (0.34600000000000003, 2),
  (0.3465, 1),
  (0.34700000000000003, 2),
  (0.348, 1),
  (0.349, 1),
  (0.35, 1),
  (0.3505, 2),
  (0.3515, 2),
  (0.35200000000000004, 1),
  (0.3525, 1),
  (0.3535, 2),
  (0.354, 1),
  (0.355, 1),
  (0.3555, 1),
  (0.3575, 1),
  (0.358, 2),
  (0.359, 1),
  (0.3595, 3),
  (0.361, 2),
  (0.3615, 2),
  (0.36200000000000004, 1),
  (0.3625, 4),
  (0.3645, 3),
  (0.365, 3),
  (0.366, 3),
  (0.36700000000000005, 1),
  (0.3675, 4),
  (0.368, 1),
  (0.3685, 5),
  (0.369, 2),
  (0.3705, 2),
  (0.371, 1),
  (0.3715, 2),
  (0.37200000000000005, 2),
  (0.3735, 1),
  (0.3745, 1),
  (0.375, 1),
  (0.3755, 2),
  (0.376, 1),
  (0.377, 1),
  (0.37799999999999995, 4),
  (0.3785, 1),
  (0.379, 2),
  (0.3795, 2),
  (0.38, 2),
  (0.3805, 1),
  (0.381, 1),
  (0.382, 1),
  (0.38299999999999995, 1),
  (0.384, 3),
  (0.385, 2),
  (0.3855, 1),
  (0.386, 1),
  (0.3865, 1),
  (0.3875, 1),
  (0.38799999999999996, 2),
  (0.3885, 1),
  (0.389, 1),
  (0.3895, 1),
  (0.39, 1),
  (0.3905, 1),
  (0.3915, 1),
  (0.3925, 1),
  (0.39299999999999996, 4),
  (0.3935, 1),
  (0.39399999999999996, 3),
  (0.3945, 1),
  (0.3955, 1),
  (0.396, 1),
  (0.3965, 1),
  (0.397, 1),
  (0.3975, 1),
  (0.39799999999999996, 1),
  (0.3995, 1),
  (0.4, 1),
  (0.4005, 1),
  (0.401, 1),
  (0.4015, 3),
  (0.402, 1),
  (0.4025, 1),
  (0.4035, 1),
  (0.4045, 1),
  (0.405, 1),
  (0.4055, 1),
  (0.406, 3),
  (0.40700000000000003, 2),
  (0.4075, 3),
  (0.4085, 1),
  (0.409, 2),
  (0.4095, 1),
  (0.41100000000000003, 4),
  (0.4115, 1),
  (0.41200000000000003, 1),
  (0.413, 2),
  (0.414, 1),
  (0.415, 2),
  (0.4155, 4),
  (0.41600000000000004, 1),
  (0.4165, 1),
  (0.41700000000000004, 2),
  (0.4175, 1),
  (0.418, 1),
  (0.4195, 2),
  (0.4215, 3),
  (0.42200000000000004, 1),
  (0.4225, 1),
  (0.4235, 1),
  (0.425, 2),
  (0.4255, 1),
  (0.426, 1),
  (0.4265, 2),
  (0.428, 1),
  (0.4285, 1),
  (0.4295, 1),
  (0.43, 1),
  (0.4305, 1),
  (0.431, 1),
  (0.4315, 1),
  (0.4325, 1),
  (0.433, 1),
  (0.434, 2),
  (0.435, 2),
  (0.4355, 1),
  (0.436, 1),
  (0.4365, 2),
  (0.43700000000000006, 1),
  (0.43799999999999994, 1),
  (0.4385, 3),
  (0.439, 2),
  (0.44, 2),
  (0.4405, 3),
  (0.441, 3),
  (0.4415, 2),
  (0.442, 1),
  (0.4425, 2),
  (0.44299999999999995, 1),
  (0.444, 1),
  (0.4445, 2),
  (0.445, 1),
  (0.4465, 1),
  (0.447, 2),
  (0.4475, 4),
  (0.44799999999999995, 1),
  (0.4485, 1),
  (0.449, 2),
  (0.4495, 4),
  (0.45, 1),
  (0.451, 1),
  (0.452, 3),
  (0.4535, 1),
  (0.45399999999999996, 1),
  (0.4545, 2),
  (0.4555, 1),
  (0.456, 2),
  (0.4565, 2),
  (0.457, 2),
  (0.45799999999999996, 2),
  (0.4585, 2),
  (0.45899999999999996, 1),
  (0.4595, 1),
  (0.46, 1),
  (0.461, 1),
  (0.4615, 2),
  (0.462, 2),
  (0.4625, 2),
  (0.4635, 1),
  (0.46399999999999997, 2),
  (0.4645, 1),
  (0.465, 1),
  (0.4655, 1),
  (0.466, 2),
  (0.4665, 2),
  (0.467, 2),
  (0.4675, 1),
  (0.46799999999999997, 3),
  (0.47, 1),
  (0.4705, 1),
  (0.47100000000000003, 2),
  (0.4715, 1),
  (0.4725, 4),
  (0.474, 4),
  (0.4745, 2),
  (0.475, 1),
  (0.47600000000000003, 1),
  (0.4775, 6),
  (0.478, 3),
  (0.479, 1),
  (0.4795, 1),
  (0.48, 2),
  (0.48200000000000004, 1),
  (0.4825, 1),
  (0.4835, 1),
  (0.484, 1),
  (0.4845, 1),
  (0.486, 2),
  (0.4865, 1),
  (0.48700000000000004, 3),
  (0.488, 2),
  (0.4885, 2),
  (0.4895, 3),
  (0.49, 1),
  (0.4905, 2),
  (0.491, 1),
  (0.4915, 1),
  (0.49200000000000005, 1),
  (0.4925, 1),
  (0.4935, 3),
  (0.494, 5),
  (0.495, 2),
  (0.4955, 2),
  (0.4965, 2),
  (0.49700000000000005, 1),
  (0.4975, 1),
  (0.498, 3),
  (0.4985, 1),
  (0.499, 2),
  (0.4995, 1),
  (0.5, 2),
  (0.501, 3),
  (0.5035, 1),
  (0.5055, 1),
  (0.5065, 1),
  (0.507, 1),
  (0.5075, 1),
  (0.5085, 1),
  (0.5095, 2),
  (0.51, 2),
  (0.5105, 1),
  (0.511, 2),
  (0.5115, 1),
  (0.512, 1),
  (0.5125, 2),
  (0.513, 1),
  (0.5135, 2),
  (0.514, 4),
  (0.515, 4),
  (0.5155, 2),
  (0.516, 2),
  (0.5165, 1),
  (0.5175, 1),
  (0.5185, 2),
  (0.519, 2),
  (0.5195, 1),
  (0.5205, 3),
  (0.521, 2),
  (0.5215, 2),
  (0.522, 2),
  (0.5225, 4),
  (0.523, 2),
  (0.524, 1),
  (0.525, 2),
  (0.5255, 1),
  (0.526, 1),
  (0.5265, 1),
  (0.528, 3),
  (0.5285, 1),
  (0.529, 2),
  (0.53, 1),
  (0.5305, 1),
  (0.531, 1),
  (0.5315, 1),
  (0.5325, 1),
  (0.5329999999999999, 1),
  (0.5335, 1),
  (0.534, 1),
  (0.5345, 1),
  (0.536, 1),
  (0.5365, 1),
  (0.537, 2),
  (0.5379999999999999, 1),
  (0.5385, 1),
  (0.5395, 2),
  (0.5415, 3),
  (0.542, 2),
  (0.5425, 1),
  (0.5429999999999999, 1),
  (0.5435, 1),
  (0.544, 1),
  (0.5445, 2),
  (0.545, 1),
  (0.5465, 2),
  (0.547, 4),
  (0.5489999999999999, 1),
  (0.5495, 1),
  (0.551, 2),
  (0.5525, 2),
  (0.5529999999999999, 1),
  (0.5535, 1),
  (0.5539999999999999, 1),
  (0.5545, 3),
  (0.555, 1),
  (0.5555, 2),
  (0.556, 2),
  (0.5565, 1),
  (0.557, 1),
  (0.5575, 1),
  (0.5585, 3),
  (0.5589999999999999, 2),
  (0.56, 2),
  (0.5605, 2),
  (0.562, 2),
  (0.5625, 1),
  (0.563, 1),
  (0.564, 1),
  (0.565, 1),
  (0.5655, 1),
  (0.5670000000000001, 3),
  (0.568, 1),
  (0.5695, 1),
  (0.5705, 2),
  (0.5720000000000001, 1),
  (0.5725, 1),
  (0.573, 2),
  (0.5735, 2),
  (0.5745, 2),
  (0.575, 1),
  (0.5755, 2),
  (0.5765, 2),
  (0.5770000000000001, 1),
  (0.5775, 2),
  (0.578, 2),
  (0.5785, 3),
  (0.5795, 5),
  (0.58, 1),
  (0.5805, 5),
  (0.581, 2),
  (0.5815, 1),
  (0.5825, 3),
  (0.583, 1),
  (0.5835, 1),
  (0.585, 1),
  (0.5865, 1),
  (0.5870000000000001, 1),
  (0.589, 1),
  (0.5895, 2),
  (0.5905, 1),
  (0.591, 2),
  (0.5915, 1),
  (0.5920000000000001, 2),
  (0.5925, 1),
  (0.593, 1),
  (0.5935, 1),
  (0.594, 2),
  (0.5945, 2),
  (0.595, 2),
  (0.5955, 2),
  (0.596, 3),
  (0.5965, 2),
  (0.597, 2),
  (0.5975, 1),
  (0.599, 5),
  (0.5995, 1),
  (0.6005, 1),
  (0.601, 2),
  (0.6015, 2),
  (0.602, 1),
  (0.6025, 4),
  (0.6055, 1),
  (0.607, 1),
  (0.6075, 1),
  (0.608, 1),
  (0.609, 2),
  (0.6095, 1),
  (0.61, 2),
  (0.6105, 1),
  (0.6115, 2),
  (0.612, 2),
  (0.6125, 2),
  (0.614, 1),
  (0.6145, 1),
  (0.615, 1),
  (0.6155, 1),
  (0.616, 2),
  (0.617, 2),
  (0.6175, 3),
  (0.6185, 1),
  (0.619, 1),
  (0.62, 1),
  (0.6215, 2),
  (0.622, 2),
  (0.623, 1),
  (0.6235, 1),
  (0.624, 1),
  (0.6245, 2),
  (0.625, 4),
  (0.6255, 2),
  (0.6265, 1),
  (0.6275, 3),
  (0.6295, 2),
  (0.6315, 3),
  (0.632, 1),
  (0.6325, 1),
  (0.633, 1),
  (0.6335, 4),
  (0.635, 2),
  (0.6355, 1),
  (0.636, 3),
  (0.637, 1),
  (0.6375, 1),
  (0.6385, 2),
  (0.639, 1),
  (0.64, 1),
  (0.6415, 1),
  (0.642, 1),
  (0.6425, 1),
  (0.643, 1),
  (0.6435, 4),
  (0.6445, 3),
  (0.6455, 1),
  (0.6459999999999999, 2),
  (0.648, 1),
  (0.6485, 1),
  (0.649, 2),
  (0.65, 1),
  (0.6505, 1),
  (0.6509999999999999, 2),
  (0.6515, 2),
  (0.653, 1),
  (0.654, 1),
  (0.6545, 1),
  (0.655, 2),
  (0.6555, 2),
  (0.6559999999999999, 2),
  (0.6565, 1),
  (0.657, 2),
  (0.6579999999999999, 2),
  (0.659, 1),
  (0.6595, 2),
  (0.66, 2),
  (0.6605, 1),
  (0.6615, 3),
  (0.662, 1),
  (0.6625, 1),
  (0.6629999999999999, 2),
  (0.6635, 1),
  (0.664, 2),
  (0.6645, 2),
  (0.6655, 2),
  (0.6665, 1),
  (0.667, 1),
  (0.6675, 1),
  (0.6679999999999999, 1),
  (0.669, 1),
  (0.672, 1),
  (0.6725, 2),
  (0.6729999999999999, 1),
  (0.6735, 1),
  (0.674, 1),
  (0.675, 1),
  (0.6755, 1),
  (0.6765, 5),
  (0.677, 1),
  (0.6775, 1),
  (0.6779999999999999, 1),
  (0.6795, 1),
  (0.6805, 1),
  (0.6809999999999999, 2),
  (0.6815, 1),
  (0.6829999999999999, 1),
  (0.6835, 1),
  (0.685, 1),
  (0.6855, 2),
  (0.6859999999999999, 2),
  (0.687, 1),
  (0.6875, 1),
  (0.688, 1),
  (0.6885, 2),
  (0.6905, 1),
  (0.6925, 1),
  (0.6940000000000001, 1),
  (0.695, 1),
  (0.6955, 1),
  (0.696, 1),
  (0.6965, 3),
  (0.6975, 1),
  (0.6990000000000001, 2),
  (0.6995, 1),
  (0.7005, 1),
  (0.701, 1),
  (0.7020000000000001, 3),
  (0.7025, 1),
  (0.7035, 1),
  (0.7045, 2),
  (0.705, 1),
  (0.706, 1),
  (0.7070000000000001, 2),
  (0.7075, 1),
  (0.7085, 1),
  (0.7090000000000001, 3),
  (0.7095, 2),
  (0.711, 1),
  (0.7120000000000001, 1),
  (0.7125, 2),
  (0.7145, 1),
  (0.7155, 1),
  (0.7165, 2),
  (0.7170000000000001, 3),
  (0.7175, 1),
  (0.7185, 1),
  (0.72, 2),
  (0.7205, 2),
  (0.721, 1),
  (0.722, 1),
  (0.7225, 1),
  (0.723, 1),
  (0.7235, 1),
  (0.7240000000000001, 1),
  (0.7245, 1),
  (0.725, 1),
  (0.7265, 1),
  (0.7275, 1),
  (0.728, 3),
  (0.7285, 1),
  (0.7305, 2),
  (0.7315, 1),
  (0.732, 1),
  (0.7325, 2),
  (0.7345, 1),
  (0.7355, 1),
  (0.7365, 3),
  (0.737, 2),
  (0.738, 3),
  (0.7385, 2),
  (0.7390000000000001, 1),
  (0.7395, 2),
  (0.74, 2),
  (0.7405, 1),
  (0.741, 1),
  (0.742, 2),
  (0.7425, 1),
  (0.743, 1),
  (0.7440000000000001, 2),
  (0.745, 2),
  (0.7455, 1),
  (0.7465, 1),
  (0.7485, 2),
  (0.7495, 1),
  (0.7505, 1),
  (0.7509999999999999, 2),
  (0.752, 1),
  (0.753, 2),
  (0.7535, 2),

In [42]:
ex.get_distinct_value(sdf, 'sex')

array(['M', 'I'], dtype=object)